(function(){
'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},d="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;
function ba(a,b){if(b){var c=d;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];f in c||(c[f]={});c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
ba("String.prototype.repeat",function(a){return a?a:function(a){var c;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");c=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var e="";a;)if(a&1&&(e+=c),a>>>=1)c+=c;return e}});function ca(){ca=function(){};d.Symbol||(d.Symbol=da)}var ea=0;function da(a){return"jscomp_symbol_"+(a||"")+ea++}
function fa(){ca();var a=d.Symbol.iterator;a||(a=d.Symbol.iterator=d.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ga(this)}});fa=function(){}}function ga(a){var b=0;return ha(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ha(a){fa();a={next:a};a[d.Symbol.iterator]=function(){return this};return a}
ba("Array.from",function(a){return a?a:function(a,c,e){fa();c=c?c:function(a){return a};var f=[],g=a[Symbol.iterator];if("function"==typeof g)for(a=g.call(a);!(g=a.next()).done;)f.push(c.call(e,g.value));else for(var g=a.length,k=0;k<g;k++)f.push(c.call(e,a[k]));return f}});
function ia(a,b){fa();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}ba("Array.prototype.keys",function(a){return a?a:function(){return ia(this,function(a){return a})}});
ba("Array.prototype.fill",function(a){return a?a:function(a,c,e){var f=this.length||0;0>c&&(c=Math.max(0,f+c));if(null==e||e>f)e=f;e=Number(e);0>e&&(e=Math.max(0,f+e));for(c=Number(c||0);c<e;c++)this[c]=a;return this}});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2cvec2:"vec2 arctan2cvec2(cvec2 v){\nreturn arctan2c(v.real,v.imag);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn vec2(dot(a,b),dot(a,vec2(-b.y,b.x)))/dot(b,b);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",
hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(dot(a,vec2(b.x,-b.y)),dot(a,b.yx));\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",powi:"float powi(float a,int b){\nif(mod(float(b),2.) < .5)\nreturn pow(abs(a),float(b));\nelse\nreturn sign(a)*pow(abs(a),float(b));\n}\n",
random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",
sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",
subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,h,m,q,t,u=!1,la,w=!1,ma=1;
function na(){function a(c){h.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){h=document.createElement("canvas");h.id="glcanvas";h.style.display="none";h.width=h.height=0;document.body.appendChild(h);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";h.addEventListener("webglcontextcreationerror",a,!1);(q=h.getContext("webgl"))||(q=h.getContext("experimental-webgl"));
if(!q)throw new x("Could not obtain a WebGL context.\nReason: "+b);h.removeEventListener("webglcontextcreationerror",a,!1);w=q.getExtension("OES_texture_float")&&q.getExtension("OES_texture_float_linear");w||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(u=(la=q.getExtension("OES_texture_half_float"))&&q.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),w=u=!1,q.getExtension("OES_texture_half_float")&&q.getExtension("OES_texture_half_float_linear")&&q.getExtension("EXT_color_buffer_half_float")?u=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ka=!0}};function oa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,e=a.length;c<e;c++)b[c]=oa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=oa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function pa(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,e=a.length;c<e;c++)if(!pa(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(e=0;e<c.length;e++){var f=c[e];if(!pa(a[f],b[f]))return!1}return!0}return!1}function qa(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function y(a){if("boolean"===a.ctype)return z.F;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?z.m:z.f:z.g;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=y(b[0]),e=1;e<b.length;e++)c=A(c,y(b[e]));ra(c)&&(c=A(c,z.f));if(c)return{type:"list",length:b.length,h:c}}}else if("string"===a.ctype||"image"===a.ctype)return z.image;console.error("Cannot guess type of the following type:");console.log(a);return!1}var sa=0;function B(){sa++;return"_h"+sa}
function ta(a,b){if(a>h.width||b>h.height)h.width=Math.ceil(a),h.height=Math.ceil(b)}function ua(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function va(a){return ua(a,0,a.instance.canvas.clientHeight)}function wa(a){return ua(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}var xa=new Float32Array(1),ya=new Int32Array(xa.buffer);
function za(a){xa[0]=a;a=ya[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Aa(a){if(w)return new Float32Array(a);if(u){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=za(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ba(a){return w?new Float32Array(a):u?new Uint16Array(a):new Uint8Array(a)}function Ca(){return w?q.FLOAT:u?la.HALF_FLOAT_OES:q.UNSIGNED_BYTE}
function Da(a){for(var b=[],c=0;c<a.length;c++)if(w)b.push(a[c]);else if(u){var e=a[c],f=(e&31744)>>10,g=e&1023;b.push((e>>15?-1:1)*(f?31===f?g?NaN:Infinity:Math.pow(2,f-15)*(1+g/1024):g/1024*6.103515625E-5))}else b.push(a[c]/255);return b}function Ea(a){for(var b=1;b<a;)b<<=1;return b};function Fa(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.T+b.Z;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.ia(),a.readcanvaswrappers[c]=new C(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ga(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={Z:!0,T:!1,repeat:!1},b=2*c.T+c.Z,a.readcanvaswrappers[b]=new C(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}a.readPixels=a.writecanvaswrapper.readPixels.bind(a.writecanvaswrapper);return a.writecanvaswrapper}
function C(a,b){this.canvas=a;this.K=b;this.J=a.width;this.G=a.height;Ha(this);this.i=0;this.l=[];this.$=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.readPixels=this.readPixels.bind(this);a.cdyUpdate=this.ia.bind(this);a=Ba(this.V*this.L*4);for(var c=0;2>c;c++)this.l[c]=q.createTexture(),q.bindTexture(q.TEXTURE_2D,this.l[c]),q.pixelStorei(q.UNPACK_ALIGNMENT,1),q.texImage2D(q.TEXTURE_2D,0,q.RGBA,this.V,this.L,0,q.RGBA,Ca(),a),b.T?q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MIN_FILTER,
b.Z?q.LINEAR_MIPMAP_LINEAR:q.NEAREST_MIPMAP_LINEAR):q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MIN_FILTER,b.Z?q.LINEAR:q.NEAREST),q.texParameteri(q.TEXTURE_2D,q.TEXTURE_MAG_FILTER,b.Z?q.LINEAR:q.NEAREST),this.$[c]=q.createFramebuffer(),q.bindFramebuffer(q.FRAMEBUFFER,this.$[c]),q.framebufferTexture2D(q.FRAMEBUFFER,q.COLOR_ATTACHMENT0,q.TEXTURE_2D,this.l[c],0);this.Y=new Ia(ja.copytexture_v,ja.copytexture_f);b=q.createBuffer();q.bindBuffer(q.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,
1,0]);a=q.getAttribLocation(this.Y.i,"aPos");q.enableVertexAttribArray(a);c=q.getAttribLocation(this.Y.i,"aTexCoord");q.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;q.bufferData(q.ARRAY_BUFFER,f+e.byteLength,q.STATIC_DRAW);q.bufferSubData(q.ARRAY_BUFFER,0,b);q.bufferSubData(q.ARRAY_BUFFER,f,e);q.vertexAttribPointer(a,3,q.FLOAT,!1,0,0);q.vertexAttribPointer(c,2,q.FLOAT,!1,0,f)}
function Ha(a){a.V=Ea(a.J+a.J/2*(a.K.T&&a.K.repeat));a.L=Ea(a.G+a.G/2*(a.K.T&&a.K.repeat))}C.prototype.bindTexture=function(){q.bindTexture(q.TEXTURE_2D,this.l[this.i])};C.prototype.bindFramebuffer=function(){q.bindFramebuffer(q.FRAMEBUFFER,this.$[this.i^1]);this.i^=1};
C.prototype.ia=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.J,this.canvas.img.height=this.G,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.J,this.G);this.drawTo(a,0,0);this.canvas.img.generation++};
function Ja(a){if(a.canvas.live||a.canvas.ready&&!(a.generation>=a.canvas.generation)){if(a.J!=a.canvas.width||a.G!=a.canvas.height){a.J=a.canvas.width;a.G=a.canvas.height;Ha(a);for(var b=Ba(a.V*a.L*4),c=0;2>c;c++)q.bindTexture(q.TEXTURE_2D,a.l[c]),q.texImage2D(q.TEXTURE_2D,0,q.RGBA,a.V,a.L,0,q.RGBA,Ca(),b)}a.bindTexture();q.pixelStorei(q.UNPACK_FLIP_Y_WEBGL,1);a.K.repeat?(m.width=a.V,m.height=a.L,b=m.getContext("2d"),b.drawImage(a.canvas.img,0,a.L-a.G),b.drawImage(a.canvas.img,a.J,a.L-a.G),b.drawImage(a.canvas.img,
0,a.L-2*a.G),b.drawImage(a.canvas.img,a.J,a.L-2*a.G),q.texSubImage2D(q.TEXTURE_2D,0,0,0,q.RGBA,Ca(),m)):q.texSubImage2D(q.TEXTURE_2D,0,0,0,q.RGBA,Ca(),a.canvas.img);a.K.T&&q.generateMipmap(q.TEXTURE_2D);q.pixelStorei(q.UNPACK_FLIP_Y_WEBGL,0);a.generation=a.canvas.generation;console.log("Image has been loaded to GPU")}}
C.prototype.drawTo=function(a,b,c){ta(this.J,this.G);q.viewport(0,0,this.V,this.L);q.useProgram(this.Y.i);q.activeTexture(q.TEXTURE0);q.bindTexture(q.TEXTURE_2D,this.l[this.i]);this.Y.l.sampler([0]);q.bindFramebuffer(q.FRAMEBUFFER,null);q.drawArrays(q.TRIANGLE_STRIP,0,4);q.flush();a.drawImage(h,0,h.height-this.G,this.J,this.G,b,c,this.J,this.G)};
C.prototype.readPixels=function(a,b,c,e){q.bindFramebuffer(q.FRAMEBUFFER,this.$[this.i]);q.framebufferTexture2D(q.FRAMEBUFFER,q.COLOR_ATTACHMENT0,q.TEXTURE_2D,this.l[this.i],0);var f=Ba(c*e*4);q.readPixels(a,this.G-b-e,c,e,q.RGBA,Ca(),f);a=[];for(--e;0<=e;e--)a=a.concat(Da(f.slice(e*c*4,(e+1)*c*4)));return a};function Ka(a,b){this.B=a;this.K=b;La(this)}
function La(a){var b=Ma(new Na(a.B),a.K);a.l=b.A;a.C=b.C;a.da=b.da;a.Y=ja.standardFragmentHeader+b.code;a.$=ja.vshader;a.i=new Ia(a.$,a.Y);b=q.createBuffer();q.bindBuffer(q.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=q.getAttribLocation(a.i.i,"aPos");q.enableVertexAttribArray(c);a=q.getAttribLocation(a.i.i,"aTexCoord");q.enableVertexAttribArray(a);var e=new Float32Array([0,0,1,0,0,1,1,1]),f=b.byteLength;q.bufferData(q.ARRAY_BUFFER,f+e.byteLength,q.STATIC_DRAW);q.bufferSubData(q.ARRAY_BUFFER,
0,b);q.bufferSubData(q.ARRAY_BUFFER,f,e);q.vertexAttribPointer(c,3,q.FLOAT,!1,0,0);q.vertexAttribPointer(a,2,q.FLOAT,!1,0,f)}
function Oa(a){function b(a,c,e){if(a)if("function"===typeof a)switch(c){case z.g:a([e.value.real,e.value.imag]);break;case z.F:e.value?a([1]):a([0]);break;case z.m:case z.f:a([e.value.real]);break;default:if("list"===c.type&&E(c.h,z.f))a(e.value.map(function(a){return a.value.real}));else if("list"===c.type&&"list"===c.h.type&&E(c.h.h,z.f)){for(var f=[],n=0;n<c.h.length;n++)for(var r=0;r<c.length;r++)f.push(e.value[r].value[n].value.real);a(f)}else console.error("Don't know how to set uniform of type "+
F(c)+", to "+e)}else if("list"===c.type)if(1===G(c)&&I(c)){c=Pa(c.length);var v=0;for(f in c)b(a["a"+f],z.fa(c[f]),{ctype:"list",value:J(c[f]).map(function(a){return e.value[v+a]})}),v+=c[f]}else for(f=0;f<c.length;f++)b(a["a"+f],c.h,{ctype:"list",value:e.value[f].value});else console.error("Don't know how to set uniform of type "+F(c)+", to"),console.log(e)}for(var c in a.l){var e=a.B.evaluateAndVal(a.l[c].X),f=a.l[c].type;if(!E(Qa(e),f)){console.log("Type of "+c+" changed ("+F(Qa(e))+" is no subtype of  "+
F(f)+"); forcing rebuild.");La(a);q.useProgram(a.i.i);Oa(a);return}a.i.l[c]&&b(a.i.l[c],f,e)}[["rnd_",function(){return[Math.random()]}],["_lowerleft",function(){var b=va(a.B);return[b.x,b.y]}],["_lowerright",function(){var b=wa(a.B);return[b.x,b.y]}]].map(function(b){return a.i.l[b[0]]&&a.i.l[b[0]](b[1]())})}
function Ra(a){var b=0,c;for(c in a.C)for(var e in a.C[c]){q.activeTexture(q.TEXTURE0+b);var f=a.C[c][e],g=f.name,k={Z:f.U.hasOwnProperty("interpolate")?f.B.evaluateAndVal(f.U.interpolate).value:!0,T:f.U.hasOwnProperty("mipmap")?f.B.evaluateAndVal(f.U.mipmap).value:!1,repeat:f.U.hasOwnProperty("repeat")?f.B.evaluateAndVal(f.U.repeat).value:!1},f=Sa(f,k);Ja(f);f.bindTexture();[["_sampler"+g,[b]],["_ratio"+g,[f.J/f.G]],["_cropfact"+g,[f.J/f.V,f.G/f.L]],["_repeat"+g,[k.repeat]],["_mipmap"+g,[k.T]]].map(function(b){return a.i.l[b[0]]&&
a.i.l[b[0]](b[1])});b++}};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,e,f,g,k,l){if(!b.ma||b.ka<ma)b.ma=!0,b.ka=ma,b.oa=new Ka(a,b);b=b.oa;var p;a:{for(p in b.da)if(b.B.getMyfunction(p).generation>b.da[p]){console.log(p+" is outdated; forcing rebuild.");p=!1;break a}p=!0}p||La(b);var n=k/g;p=e.x+-(f.y-e.y)*n;n=e.y+(f.x-e.x)*n;ta(g,k);l?q.viewport(0,0,g,k):q.viewport(0,h.height-k,g,k);q.useProgram(b.i.i);Oa(b);e=[f.x-e.x,p-e.x,e.x,f.y-e.y,n-e.y,e.y,0,0,1];b.i.l.hasOwnProperty("transformMatrix")&&b.i.l.transformMatrix([e[0],
e[3],e[6],e[1],e[4],e[7],e[2],e[5],e[8]]);Ra(b);l?(l.bindFramebuffer(),l.generation=++l.canvas.generation):q.bindFramebuffer(q.FRAMEBUFFER,null);q.drawArrays(q.TRIANGLE_STRIP,0,4);q.flush();l&&(l.generation=Math.max(l.generation,l.canvas.generation+1))}t=a.nada;a.defineFunction("compile",1,function(b){b=Ma(new Na(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){ma++;return t});a.defineFunction("colorplot",1,function(c){na();var e=a.instance.canvas.clientWidth,
f=a.instance.canvas.clientHeight,g=a.instance.canvas.width,k=a.instance.canvas.height;b(c[0],va(a),wa(a),g,k,null);a.instance.canvas.getContext("2d").drawImage(h,0,0,g,k,0,0,e,f);return t});a.defineFunction("colorplot",3,function(c){na();var e=c[0],f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.extractPoint(a.evaluateAndVal(c[2])),k={x:Math.min(f.x,g.x),y:Math.min(f.y,g.y)},l={x:Math.max(f.x,g.x),y:Math.min(f.y,g.y)};c=a.instance.canvas.clientWidth;var p=a.instance.canvas.clientHeight,n=a.instance.canvas.width,
r=a.instance.canvas.height,v=ua(a,0,0),H=va(a),D=wa(a),D=Math.abs((f.x-g.x)/(H.x-D.x)),v=Math.abs((f.y-g.y)/(v.y-H.y));b(e,k,l,n*D,r*v,null);e=a.instance.canvas.getContext("2d");k=Math.min(f.x,g.x);f=Math.max(f.y,g.y);g=a.getInitialMatrix();e.drawImage(h,0,0,n*D,r*v,k*g.a-f*g.b+g.tx,k*g.c-f*g.d-g.ty,D*c,v*p);return t});a.defineFunction("colorplot",4,function(c){na();var e=a.extractPoint(a.evaluateAndVal(c[0])),f=a.extractPoint(a.evaluateAndVal(c[1])),g=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!f.ok||
"string"!==g.ctype)return t;var g=a.getImage(g.value,!0),k=Ga(g);b(c,e,f,g.width,g.height,k);return t});a.defineFunction("colorplot",2,function(c){na();var e=va(a),f=wa(a),g=a.evaluateAndVal(c[0]);c=c[1];if("string"!==g.ctype)return t;var g=a.getImage(g.value,!0),k=Ga(g);b(c,e,f,g.width,g.height,k);return t});a.defineFunction("setpixel",4,function(b){var e;var f=a.evaluateAndVal(b[0]),g;g=void 0===g?null:g;"string"===f.ctype?e=f.value:(console.log("argument is not a string"),e=g);f=Ta(a.evaluateAndVal(b[1]));
g=Ta(a.evaluateAndVal(b[2]));b=Ua(a.evaluateAndVal(b[3]));if(!e)return t;var k=a.getImage(e,!0),k=Ga(k);isFinite(f)&&isFinite(g)&&e&&k&&b&&(k.bindTexture(),e=[b[0],b[1],b[2],1],q.texSubImage2D(q.TEXTURE_2D,0,f,g,1,1,q.RGBA,Ca(),Aa(e)),b=k.canvas.img.getContext("2d"),k=b.createImageData(1,1),k.data.d=e,b.putImageData(k,f,g));return t})});function I(a){return"list"===a.type&&I(a.h)||E(a,z.f)}function K(a){return"list"===a.type&&K(a.h)||E(a,z.g)}function Va(a){return"constant"===a.type&&E(a,z.m)}function Wa(a){return"constant"===a.type?y(a.value):a}function G(a){return"list"===a.type?G(a.h)+1:0}function Xa(a){return a.h?Xa(a.h):a}function Ya(a,b){return G(a)===G(b)&&(0===G(a)||a.length===b.length&&Ya(a.h,b.h))}function L(a){return E(a,z.f)?z.f:E(a,z.g)?z.g:{type:"list",length:a.length,h:L(a.h)}}
function Za(a){return E(a,z.g)?z.g:{type:"list",length:a.length,h:Za(a.h)}}function M(a){return a===z.F||a===z.m||a===z.f||a===z.g||"list"===a.type&&a.h===z.f&&1<=a.length&&4>=a.length||"list"===a.type&&"list"===a.h.type&&a.h.h===z.f&&a.length===a.h.length&&2<=a.length&&4>=a.length}function ra(a){return-1!==[z.F,z.m,z.f,z.g].indexOf(a)}
function $a(a,b){return a===b||"constant"===a.type&&"constant"===b.type&&a.value.ctype===b.value.ctype&&("number"===a.value.ctype&&a.value.value.real===b.value.value.real&&a.value.value.imag===b.value.value.imag||"boolean"===a.value.ctype&&a.value.value===b.value.value)||"list"===a.type&&"list"===b.type&&a.length===b.length&&$a(a.h,b.h)}
function E(a,b){return $a(a,b)||a===z.ga?!0:a?ra(a)&&ra(b)?a<=b:"constant"===b.type?!1:"constant"===a.type?E(y(a.value),b):b===z.I?E(a,z.g)||E(a,z.O)||E(a,z.N):b===z.N||b===z.S?E(a,z.P):b===z.color?E(a,z.f)||"list"===a.type&&(3===a.length||4===a.length)&&E(a.h,z.f):"list"===a.type&&"list"===b.type&&a.length===b.length?E(a.h,b.h):!1:!1}
function A(a,b){if(!a)return b;if(!b||$a(a,b))return a;"constant"===a.type&&(a=y(a.value));"constant"===b.type&&(b=y(b.value));return ra(a)&&ra(b)?Math.max(a,b):"list"===a.type&&"list"===b.type&&a.length===b.length&&(b=A(a.h,b.h))?{type:"list",length:a.length,h:b}:!1}function N(a){return function(b){var c={},e;for(e in a){var f=a[e];c.ca=f[0];if(b.length==c.ca.length&&b.every(function(a){return function(b,c){return E(b,a.ca[c])}}(c)))return{u:c.ca,v:f[1],s:f[2]};c={ca:c.ca}}return!1}}
function ab(a){switch(a){case z.m:return N([[[z.F],z.m,O("int")]]);case z.f:return N([[[z.F],z.f,O("float")],[[z.m],z.f,O("float")]]);case z.g:return N([[[z.f],z.g,function(a){return"vec2("+a+", 0.)"}]]);case z.color:return N([[[z.f],z.color,P("float2color")],[[z.P],z.color,function(a){return"vec4("+a+",1.0)"}],[[z.aa],z.color,Q]]);case z.N:return N([[[z.O],z.N,function(a){return"vec3("+a+",1.0)"}],[[z.P],z.N,Q]]);case z.S:return N([[[z.O],z.S,function(a){return"vec3("+a+",1.0)"}],[[z.P],z.S,Q]]);
case z.I:return N([[[z.g],z.I,Q],[[z.O],z.I,Q],[[z.N],z.I,P("dehomogenize")]]);default:if("list"===a.type)return E(Xa(a),z.f)?function(b){if(E(b[0],a))return{u:b,v:a,s:Q}}:function(b){var c=b[0],e=ab(a.h)([c.h]).s;return{u:b,v:a,s:function(b,g,k){return bb(a)([J(a.length).map(function(a){return e([cb(c,a)([b],g,k)],g,k)})],g,k)}}}}console.log("no inclusionfunction ->"+F(a)+" implemented yet; using identity...");return function(b){return{u:b,v:a,s:Q}}}
function R(a){switch(a){case z.F:return"bool";case z.m:return"int";case z.f:return"float";case z.g:case z.I:return"vec2";case z.M:return"void";case z.color:return"vec4";case z.N:case z.S:return"vec3"}if("list"===a.type&&E(a.h,z.f))return 1==a.length?"float":"vec"+a.length;if("list"===a.type&&E(a.h,z.g))return"cvec"+a.length;if("list"===a.type&&"list"===a.h.type&&a.length===a.h.length&&E(a.h.h,z.f))switch(a.length){case 2:return"mat2";case 3:return"mat3";case 4:return"mat4"}if("list"===a.type&&"list"===
a.h.type&&E(a.h.h,z.f))return"mat"+a.length+"_"+a.h.length;if("list"===a.type&&"list"===a.h.type&&E(a.h.h,z.g))return"cmat"+a.length+"_"+a.h.length;if("list"===a.type)return"l"+a.length+"_"+R(a.h);console.error("No WebGL implementation for type "+F(a)+" found")}
function db(a,b){switch(b){case z.F:return R(b)+"("+a.value+")";case z.m:return R(b)+"("+(a.value.real|0)+")";case z.f:return R(b)+"("+a.value.real+")";case z.g:return R(b)+"("+a.value.real+", "+a.value.imag+")";case z.color:return a=a.value.real,"vec4("+a+","+a+","+a+",1.)";default:console.error("Dont know how to paste values of Type "+F(b)+" yet.")}};var S={};function eb(a,b,c){if(!c.mark("includedfunctions",a)){for(var e in S[a])eb(S[a][e],b,c);c.add("includedfunctions",a,function(){return ja[a]})}}function P(a){return function(b,c,e){eb(a,c,e);return O(a)(b)}};function J(a){return Array.from(Array(a).keys())}function Pa(a){return 4>=a?[a]:5==a?[2,3]:Pa(a-4).concat([4])}function gb(a){var b=Xa(a),c=G(a);return 1==c&&E(b,z.f)?Pa(a.length).map(function(a,b){return{type:z.fa(a),name:"a"+b}}):1<=c?J(a.length).map(function(b){return{type:a.h,name:"a"+b}}):[]}function T(a,b){if(!M(a)){var c=R(a);b.add("structs",c,function(){return"struct "+c+" { "+gb(a).map(function(a){return T(a.type,b)||R(a.type)+" "+a.name+";"}).join("")+"};"})}}
function hb(a,b,c){if(!M(a)){var e=a.length,f=a.h.length;c.add("functions","mult"+e+"_"+f,function(){return"vec"+e+" mult"+e+"_"+f+"(mat"+e+"_"+f+" a, vec"+f+" b){return "+ib(e)(J(e).map(function(a){return jb(f)(["a.a"+a,"b"],b,c)}),b,c)+";}"})}}
function kb(a,b,c){if(!M(a)){var e=a.length,f="sum"+R(a);c.add("functions",f,function(){return R(a.h)+" "+f+"("+R(a)+" a){"+(R(a.h)+" res = "+lb(a.h,0)([],b,c)+";\n      "+J(e).map(function(e){return mb(a.h)(["res",cb(a,e)(["a",e],b,c)],b,c)}).join("\n")+"\n        return res;\n    }")})}}
function nb(a,b,c){var e=a.length,f=a.h.length;c.add("functions","multc"+e+"_"+f,function(){return"cvec"+e+" multc"+e+"_"+f+"(cmat"+e+"_"+f+" a, cvec"+f+" b){\n        return cvec"+e+"("+J(e).map(function(a){return ob(f)(["a.a"+a,"b"],b,c)})+");\n    }\n    "})}function pb(a,b){2<=a&&4>=a||b.add("functions","dot"+a,function(){return"float dot"+a+"(vec"+a+" a, vec"+a+" b) {\n    return "+Pa(a).map(function(a,b){return"dot(a.a"+b+",b.a"+b+")"}).join("+")+"; }\n    "})}
function qb(a,b){b.add("functions","cdot"+a,function(){return"vec2 cdot"+a+"(cvec"+a+" a, cvec"+a+" b) {\n      return "+J(a).map(function(a){return"vec2(dot(a.a"+a+",vec2(b.a"+a+".x,-b.a"+a+".y)), dot(a.a"+a+",b.a"+a+".yx))"}).join("+\n")+";\n    }\n    "})}
function rb(a,b,c){var e="add"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"("+R(a)+" a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return R(a.type)+"("+mb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n      }"})}
function sb(a,b,c){var e="sub"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"("+R(a)+" a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return R(a.type)+"("+tb(a.type)(["a."+a.name,"b."+a.name],b,c)+")"}).join(",")+");\n    }"})}function ub(a,b,c){var e="scalarmult"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"(float a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return R(a.type)+"("+vb(a.type)(["a","b."+a.name],b,c)+")"}).join(",")+");\n    }"})}
function wb(a,b,c){eb("multc",b,c);var e="cscalarmult"+R(a);c.add("functions",e,function(){return R(a)+" "+e+"(vec2 a, "+R(a)+" b) {\n    return "+R(a)+"("+gb(a).map(function(a){return""+xb(a.type)(["a","b."+a.name],b,c)}).join(",")+");\n    }"})}
function yb(a){if(a===z.g)return P("multc");if(M(a))return U("*");var b=Xa(a);if(E(b,z.f))return function(b,e,f){return hb(a,e,f)||"mult"+a.length+"_"+a.h.length+"("+b.join(",")+")"};if(b===z.g)return function(b,e,f){return nb(a,e,f)||"multc"+a.length+"_"+a.h.length+"("+b.join(",")+")"}}function jb(a){return function(b,c,e){return pb(a,e)||"dot"+(2<=a&&4>=a?"":a)+"("+b.join(",")+")"}}function ob(a){return function(b,c,e){return qb(a,e)||"cdot"+a+"("+b.join(",")+")"}}
function mb(a){return M(a)?U("+"):function(b,c,e){return rb(a,c,e)||"add"+R(a)+"("+b.join(",")+")"}}function tb(a){return M(a)?U("-"):function(b,c,e){return sb(a,c,e)||"sub"+R(a)+"("+b.join(",")+")"}}function zb(a){return I(a)&&1==G(a)?function(b,c,e){return jb(a.length)([b[0],ib(a.length)(Array(a.length).fill("1."),c,e)],c,e)}:function(b,c,e){return kb(a,c,e)||"sum"+R(a)+"("+b.join(",")+")"}}
function ib(a){if(2<=a&&4>=a)return function(b){return"vec"+a+"("+b.join(",")+")"};if(1==a)return function(a){return"float("+a.join(",")+")"};var b=0;return function(c,e,f){return T(z.fa(a),f)||"vec"+a+"("+Pa(a).map(function(a){return"vec"+a+"("+J(a).map(function(){return++b&&c[b-1]}).join(",")+")"}).join(",")+")"}}
function bb(a){var b=G(a);if(M(a)){if(2==b){var c=a.length;if(c==a.h.length&&2<=c&&4>=c)return function(a){return"mat"+c+"("+J(c).map(function(b){return"vec"+c+"("+J(c).map(function(c){return a[c]+"["+b+"]"}).join(",")+")"}).join(",")}}return function(b){return R(a)+"("+b.join(",")+")"}}return 1==b&&I(a)?ib(a.length):function(b,c,g){return T(a,g)||R(a)+"("+b.join(",")+")"}}function cb(a,b){return 1==G(a)&&I(a)?Ab(a.length,b):function(a){return"("+a[0]+").a"+b}}
function lb(a,b){return M(a)?function(){return R(a)+"(float("+b+"))"}:function(c,e,f){return bb(a)+"("+gb(a).map(function(a){return lb(a.type,b)(c,e,f)}).join(",")+")"}}function Ab(a,b){return function(c){if(1==a)return"("+c[0]+")";if(2<=a&&4>=a)return"("+c[0]+")["+b+"]";var e;a:{e=b;var f=Pa(a),g;for(g in f)if(f[g]<=e)e-=f[g];else{e={first:g,second:e};break a}console.error("Accessing index out of range");e=void 0}return"("+c[0]+").a"+e.first+"["+e.second+"]"}}
function vb(a){return M(a)?U("*"):function(b,c,e){return ub(a,c,e)||"scalarmult"+R(a)+"("+b.join(",")+")"}}function xb(a){return a===z.g?P("multc"):function(b,c,e){return wb(a,c,e)||"cscalarmult"+R(a)+"("+b.join(",")+")"}};function V(a,b){return{type:"list",length:a,h:b}}function Qa(a){return{type:"constant",value:a}}var z={F:1,m:2,f:3,g:4,M:5,color:6,N:7,S:8,I:9,image:10,O:V(2,3),P:V(3,3),aa:V(4,3),fa:function(a){return V(a,3)},ja:function(a){return V(a,4)},qa:V(2,V(2,3)),ra:V(3,V(3,3)),sa:V(4,V(4,3)),ga:18};Object.freeze(z);
function F(a){return 1<=a&&10>=a?"bool int float complex voidt color point line coordinate2d image".split(" ")[a-1]:"list"===a.type?F(a.h)+"["+a.length+"]":"constant"===a.type?"const["+JSON.stringify(a.value.value)+"]":JSON.stringify(a)}function O(a){return function(b){return qa(a)+"("+b+")"}}function U(a){return function(b){return"("+b.join(a)+")"}}function Q(a){return a}var W={};W.join=N([[z.N,z.N],z.S,O("cross")]);W.meet=N([[z.S,z.S],z.N,O("cross")]);
W["if"]=function(a){if(!a.every(function(a){return a}))return!1;if(2===a.length)return{u:a,v:a[1],s:function(a){return"if("+a[0]+") {"+a[1]+";}"}};if(3===a.length){var b=A(a[1],a[2]);return b?{u:[z.F,b,b],v:b,s:function(a){return"("+a[0]+" ? "+a[1]+" : "+a[2]+")"}}:{u:a,v:z.M,s:function(a){return"if("+a[0]+") {"+a[1]+";} else {"+a[2]+";}"}}}return!1};W["="]=function(a){a=A(a[0],a[1]);return{u:a,v:a,s:function(a){return a[0]+" = "+a[1]+";"}}};
W[";"]=function(a){return{u:a,v:a[1]!==z.M?a[1]:a[0],s:function(a){return a[0]+" ; "+a[1]+";"}}};W.repeat=function(a){return 2!=a.length&&3!=a.length||!Va(a[0])?!1:{u:a,v:a[a.length-1],s:function(){return""}}};W.forall=function(a){return 2!=a.length&&3!=a.length||"list"!==a[0].type?!1:{u:a,v:a[a.length-1],s:function(){return""}}};W.apply=function(a){return 2!=a.length&&3!=a.length||"list"!==a[0].type?!1:{u:a,v:V(a[0].length,a[a.length-1]),s:function(){return""}}};
W.sum=function(a){return 1==a.length&&(I(a[0])||K(a[0]))?{u:a,v:a[0].h,s:zb(a[0])}:!1};W.regional=function(a){return{u:a,v:z.M,s:function(){return""}}};W.sqrt=N([[[z.f],z.g,P("sqrtf")],[[z.g],z.g,P("sqrtc")]]);W.abs=N([[[z.f],z.f,O("abs")],[[z.g],z.f,O("length")],[[z.O],z.f,O("length")],[[z.P],z.f,O("length")],[[z.aa],z.f,O("length")]]);W.abs_infix=W.abs;
W.dist=N([[[z.f,z.f],z.f,function(a){return O("abs")(U("-")(a))}],[[z.g,z.g],z.f,function(a){return O("length")(U("-")(a))}],[[z.O,z.O],z.f,function(a){return O("length")(U("-")(a))}],[[z.P,z.P],z.f,function(a){return O("length")(U("-")(a))}],[[z.aa,z.aa],z.f,function(a){return O("length")(U("-")(a))}]]);W.dist_infix=W.dist;W.sin=N([[[z.f],z.f,O("sin")],[[z.g],z.g,P("sinc")]]);W.cos=N([[[z.f],z.f,O("cos")],[[z.g],z.g,P("cosc")]]);W.tan=N([[[z.f],z.f,O("tan")],[[z.g],z.g,P("tanc")]]);
W.exp=N([[[z.f],z.f,O("exp")],[[z.g],z.g,P("expc")]]);W.arctan=N([[[z.f],z.f,O("atan")],[[z.g],z.g,P("arctanc")]]);W.log=N([[[z.f],z.g,P("logr")],[[z.g],z.g,P("logc")]]);var Bb=[2,3,4].map(function(a){return V(a,z.f)}).concat([2,3,4].map(function(a){return V(a,V(a,z.f))})),Cb=[z.m,z.f,z.g].concat(Bb);W.add=function(a){var b=N(Cb.map(function(a){return[[a,a],a,U("+")]}))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return I(a)||K(a)})&&Ya(b,a))return a=A(L(b),L(a)),{u:[a,a],v:a,s:mb(a)}};
W.sub=function(a){var b=N(Cb.map(function(a){return[[a,a],a,U("-")]}).concat(Cb.map(function(a){return[[z.M,a],a,U("-")]})))(a);if(b)return b;b=a[0];a=a[1];if([b,a].every(function(a){return I(a)||K(a)})&&Ya(b,a))return a=A(L(b),L(a)),{u:[a,a],v:a,s:tb(a)}};W["+"]=W.add;W["-"]=W.sub;W._=function(a){var b=a[0];if("list"===b.type&&Va(a[1])){var c=Number(a[1].value.value.real);if(1<=Math.abs(c)&&Math.abs(c)<=b.length)return 0<c&&--c,0>c&&(c=b.length-c),{u:a,v:b.h,s:cb(b,c)}}return!1};
W.mult=function(a){var b=N([[[z.m,z.m],z.m,U("*")],[[z.f,z.f],z.f,U("*")],[[z.g,z.g],z.g,P("multc")]])(a);if(b)return b;if(2!==a.length)return!1;var b=a[0],c=a[1];if([b,c].every(function(a){return"list"===a.type&&E(a.h,z.f)})&&b.length===c.length)return a=L(b),M(a)?{u:[a,a],v:z.f,s:O("dot")}:{u:[a,a],v:z.f,s:jb(b.length)};if([b,c].every(function(a){return"list"===a.type&&E(a.h,z.g)})&&b.length===c.length)return a=Za(b),{u:[a,a],v:z.g,s:ob(b.length)};if(I(b)&&2===G(b)&&I(c)&&1===G(c)&&b.h.length===
c.length)return{u:[L(b),L(c)],v:z.fa(b.length),s:yb(L(b))};if(K(b)&&2===G(b)&&K(c)&&1===G(c)&&b.h.length===c.length)return{u:[Za(b),Za(c)],v:z.ja(b.length),s:yb(Za(b))};for(b={H:0};2>b.H;b={W:b.W,H:b.H,ba:b.ba},b.H++){if(E(a[0^b.H],z.f)&&(I(a[1^b.H])||K(a[1^b.H])))return b.W=L(a[1^b.H]),{u:b.H?[b.W,z.f]:[z.f,b.W],v:b.W,s:function(a){return function(b,c,k){return vb(a.W)([b[0^a.H],b[1^a.H]],c,k)}}(b)};if(E(a[0^b.H],z.g)&&K(a[1^b.H]))return b.ba=Za(a[1^b.H]),{u:b.H?[b.ba,z.g]:[z.g,b.ba],v:b.ba,s:function(a){return function(b,
c,k){return xb(a.ba)([b[0^a.H],b[1^a.H]],c,k)}}(b)}}};W["*"]=W.mult;W.div=function(a){var b=N([[[z.f,z.f],z.f,U("/")],[[z.g,z.g],z.g,P("divc")]])(a);return b?b:E(a[1],z.f)&&K(a[0])&&(a=L(a[0]),M(a))?{u:[a,z.f],v:a,s:U("/")}:!1};W["/"]=W.div;W.re=N([[[z.g],z.f,P("realc")]]);W.im=N([[[z.g],z.f,P("imagc")]]);W.floor=N([[[z.f],z.m,function(a){return"int(floor("+a+"))"}],[[z.g],z.g,O("floor")]]);W.round=N([[[z.f],z.m,function(a){return"int(floor("+a+"+.5))"}],[[z.g],z.g,function(a){return"floor("+a+"+vec2(.5))"}]]);
W.ceil=N([[[z.f],z.m,function(a){return"int(ceil("+a+"))"}],[[z.g],z.g,O("ceil")]]);W.mod=N([[[z.m,z.m],z.m,function(a,b){return"int("+O("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[[z.f,z.f],z.f,O("mod")],[[z.g,z.g],z.g,P("mod")]]);W.random=N([[[],z.f,P("random")],[[z.f],z.f,function(a,b){return P("random")([],b)+"*"+a[0]}],[[z.g],z.g,function(a,b){return"vec2("+P("random")([],b)+","+P("random")([],b)+")*"+a[0]}]]);
W.arctan2=N([[[z.f,z.f],z.f,function(a){return"atan("+a[1]+", "+a[0]+")"}],[[z.g,z.g],z.g,P("arctan2c")],[[z.g],z.f,P("arctan2vec2")],[[z.O],z.f,P("arctan2vec2")],[[z.ja(2)],z.g,P("arctan2cvec2")]]);["red","green","blue","gray","hue"].forEach(function(a){W[a]=N([[[z.f],z.P,P(a)]])});W.grey=W.gray;W.min=N([[[z.m,z.m],z.m,O("min")],[[z.f,z.f],z.f,O("min")]]);W.max=N([[[z.m,z.m],z.m,O("max")],[[z.f,z.f],z.f,O("max")]]);W.complex=N([[[z.O],z.g,Q]]);W.pow=N([[[z.f,z.m],z.f,P("powi")],[[z.g,z.g],z.g,P("powc")]]);
W["^"]=W.pow;W.re=N([[[z.g],z.f,function(a){return"("+a+").x"}]]);W.conjugate=N([[[z.g],z.g,P("conjugate")]]);W.im=N([[[z.g],z.f,function(a){return"("+a+").y"}]]);W.genList=function(a){var b=a.length;if(0<b){var c=!1,e;for(e in a)c=A(c,a[e]);if(c)return a=V(b,c),{u:Array(b).fill(c),v:a,s:bb(a)}}return!1};W["&"]=N([[[z.F,z.F],z.F,U("&&")]]);W["%"]=N([[[z.F,z.F],z.F,U("||")]]);[">","<",">=","<=","=="].forEach(function(a){W[a]=N([[[z.m,z.m],z.F,U(a)],[[z.f,z.f],z.F,U(a)]])});
W.imagergb=N([[[z.image,z.I],z.P,Db],[[z.I,z.I,z.image,z.I],z.P,Eb]]);W.imagergba=N([[[z.image,z.I],z.aa,Fb],[[z.I,z.I,z.image,z.I],z.aa,Gb]]);Object.freeze(W);S.powc=["expc","multc","logc"];S.sqrtc=["expc","multc","logc"];S.arccosc=["multc","negc","sqrtc","addc","logc"];S.arcsinc=["multc","negc","sqrtc","addc","logc"];S.tanc=["sinc","cosc","divc"];S.arctanc=["logc","addc","multc","subc"];S.arctan2c=["logc","divc","sqrtc","multc"];S.arctan2vec2c=["arctan2c"];S.hue=["hsv2rgb"];Object.freeze(S);function Na(a){this.j={};this.A={};this.i={};this.K=!1;this.l={};this.B=a;this.C={}}Na.prototype.add=function(a,b,c){this.mark(a,b);this.i[a].ha[b]||(this.i[a].ha[b]=c(),this.i[a].ea[b]=!0,this.i[a].order.push(b))};Na.prototype.mark=function(a,b){this.i[a]||(this.i[a]={order:[],ea:{},ha:{}});var c=this.i[a].ea[b]||!1;this.i[a].ea[b]=!0;return c};function Hb(a,b){return a.i[b]?a.i[b].order.map(function(c){return a.i[b].ha[c]}).join("\n"):"\n"}
function X(a,b,c,e){if($a(c,e)||c===z.ga)return b;if(E(c,e)){if("constant"===c.type)return db(c.value,e);var f=ab(e)([c]);if(!f)return console.error("cannot find an implementation for "+F(c)+" -> "+F(e)+", using identity"),b;e=f.s;return e(X(a,b,c,f.u[0]),{},a)}console.error(F(c)+" is no subtype of "+F(e)+" (trying to cast the term "+b+")");return b}function Ib(a,b,c){a.j[b]||(a.j[b]={});a.j[b].R||(a.j[b].R=[]);a.j[b].w||(a.j[b].w=!1);a.hasOwnProperty("global")||(a.j[b].global=c)}
function Jb(a,b){var c=b.D;if(b.isuniform)return a.A[b.uvariable].type;if("variable"===b.ctype)return b=b.name,b=c[b]||b,a.j[b].w;if("function"===b.ctype&&a.l.hasOwnProperty(b.oper))return a.j[c[b.oper]].w;if("number"===b.ctype)return Qa(b);if("void"===b.ctype)return z.M;if("field"===b.ctype)return z.f;if("string"===b.ctype)return z.image;if("function"===b.ctype||"infix"===b.ctype){for(var c=Array(b.args.length),e=0;e<b.args.length;e++)c[e]=Y(a,b.args[e]);a=qa(b.oper);return(a=W[a]?W[a](c):!1)?a.v:
!1}console.error("Don't know how to compute type of");console.log(b);return!1}function Y(a,b){a.K&&b.hasOwnProperty("computedType")||(b.computedType=Jb(a,b));return b.computedType}
function Kb(a,b){function c(a,b,c){var e={},g;for(g in a)e[g]=a[g];a=B();Ib(k,a,!1);f[a].w=c;f[a].na=!0;e[b]=a;return e}function e(a,b,n){a.D=b;for(var r in a.args)e(a.args[r],1<=r&&"repeat$2"===a.oper?c(b,"#",z.m):1<=r&&"repeat$3"===a.oper?c(b,a.args[1].name,z.m):1<=r&&("forall$2"===a.oper||"apply$2"===a.oper)?c(b,"#",!1):1<=r&&("forall$3"===a.oper||"apply$3"===a.oper)?c(b,a.args[1].name,!1):b,n);"field"===a.ctype&&e(a.obj,b,n);if("="===a.oper){var v=a.args[0].name,v=b[v]||v;Ib(k,v,!0);f[v].R.push(a.args[1])}else if(a.oper&&
"regional"===qa(a.oper)&&"global"!=n)for(var H in a.args)v=a.args[H].name,r=B(),b[v]=r,g[n].j||(g[n].j=[]),g[n].j.push(r),Ib(k,r,!1);else if("forall$2"===a.oper||"apply$2"===a.oper||"forall$3"===a.oper||"apply$3"===a.oper)f[2===a.args.length?a.args[1].D["#"]:a.args[2].D[a.args[1].name]].R.push({ctype:"infix",oper:"_",args:[a.args[0],{ctype:"number",value:{real:1,imag:0}}],D:a.args[0].D});else if("function"===a.ctype&&g.hasOwnProperty(a.oper)){n=a.oper;H=n.replace("$","_");Ib(k,H,!1);b[n]=H;b={};for(v in g[n].arglist){r=
g[n].arglist[v].name;var D=H+"_"+r;b[r]=D;Ib(k,D,!1);f[D].R.push(a.args[v])}g[n].pa||(g[n].pa=!0,e(g[n].body,b,n),f[H].R.push(g[n].body))}}var f=a.j,g=a.l,k=a;e(b,{"#":"cgl_pixel"},"global")}
function Lb(a,b){function c(a){if(a.hasOwnProperty("dependsOnPixel"))return a.dependsOnPixel;if("variable"===a.ctype){var b=a.name,b=a.D[b]||b;return k[b]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}b=["random","verbatimglsl"];if("function"===a.ctype&&-1!=b.indexOf(qa(a.oper)))return a.dependsOnPixel=!0;if("repeat$2"===a.oper||"forall$2"===a.oper||"apply$2"===a.oper)return c(a.args[1])?(k[a.args[1].D["#"]]=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;if("repeat$3"===a.oper||"forall$3"===a.oper||"apply$3"===
a.oper)return c(a.args[2])?(k[a.args[2].D[a.args[1].name]]=!0,a.args[1].dependsOnPixel=!0,a.dependsOnPixel=!0):a.dependsOnPixel=!1;for(var e in a.args)if(c(a.args[e]))return a.dependsOnPixel=!0;return"function"===a.ctype&&g.hasOwnProperty(a.oper)&&c(g[a.oper].body)?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj):a.dependsOnPixel=!1}function e(a,b){if(c(a)){for(var f in a.args)e(a.args[f],b||"repeat$2"===a.oper&&0==f||"repeat$3"===a.oper&&0==f||"_"===a.oper&&1==f);"field"===a.ctype&&
e(a.obj,b);"function"===a.ctype&&g.hasOwnProperty(a.oper)&&(a=a.oper,p.hasOwnProperty(a)||(p[a]=!0,e(g[a].body,b)))}else if("number"!==a.ctype&&"void"!==a.ctype){f=!1;var k,l;for(l in n)!f&&pa(a,n[l].X)&&(f=!0,k=l);f||(k=B(),n[k]={X:a,type:!1,la:b});a.isuniform=!0;a.uvariable=k}}var f=a.j,g=a.l,k={cgl_pixel:!0},l;for(l in f)if(1<=f[l].R.length||f[l].na)k[l]=!0;c(b);var p={"":!0},n=a.A;e(b,!1)}
function Mb(a,b){if("function"===b.ctype&&!a.l.hasOwnProperty(b.oper)&&null!==a.B.getMyfunction(b.oper)){var c=b.oper;a.l[c]=oa(a.B.getMyfunction(c));Mb(a,a.l[c].body)}for(var e in b.args)Mb(a,b.args[e])}
function Z(a,b,c){if(b.isuniform){b=b.uvariable;var e=a.A[b].type;return c?{code:"",o:"constant"===e.type?db(e.value,Wa(e)):b,type:e}:{code:""}}if(";"===b.oper){for(var e={type:z.M,o:""},f="",g=b.args.length-1,k=g;0<=k;k--)"void"===b.args[k].ctype&&g--;for(k=0;k<=g;k++)e=Z(a,b.args[k],c&&k===g),f+=e.code;return c?{code:f,o:e.o,type:e.type}:{code:f}}if("="===b.oper)return e=Z(a,b.args[1],!0),f=b.args[0].name,f=b.D[f]||f,b=f+" = "+X(a,e.o,e.type,Y(a,b.args[0])),c?{code:e.code,o:b,type:a.j[f].w}:{code:e.code+
b+";\n"};if("repeat$2"===b.oper||"repeat$3"===b.oper){f=Z(a,b.args[0],!0);if("constant"!==f.type.type)return console.error("repeat possible only for fixed constant number in GLSL"),!1;e="repeat$2"===b.oper?b.args[1].D["#"]:b.args[2].D[b.args[1].name];f=f.o;b=Z(a,b.args["repeat$2"===b.oper?1:2],c);k=g="";c&&(k=B(),g+=R(b.type)+" "+k+";");g=g+("for(int "+e+"=1; "+e+" <= "+f+"; "+e+"++) {\n")+b.code;c&&(g+=k+" = "+b.o+";\n");g+="}\n";return c?{code:g,o:k,type:b.type}:{code:g}}if("forall$2"===b.oper||
"forall$3"===b.oper||"apply$2"===b.oper||"apply$3"===b.oper){e=Z(a,b.args[0],!0);if("list"!==e.type.type)return console.error(b.oper+" only possible for lists"),!1;var f=2===b.args.length?b.args[1].D["#"]:b.args[2].D[b.args[1].name],g=a.j[f].w,k=Z(a,b.args[2===b.args.length?1:2],c),l="",p="",n=!1;c&&(n="forall$2"===b.oper||"forall$3"===b.oper?k.type:V(e.type.length,k.type),p=B(),l+=R(n)+" "+p+";");var l=l+e.code,r=e.o;!a.j[r]&&!a.A[r]&&2<=e.type.length&&(r=B(),l+=R(e.type)+" "+r+" = "+e.o+";\n");
for(var l=l+(R(g)+" "+f+";\n"),v=0;v<e.type.length;v++)l+=f+" = "+cb(e.type,v)([r],[],a)+";\n",l+=k.code,c&&("forall$2"===b.oper||"forall$3"===b.oper?v===e.type.length-1&&(l+=p+" = "+k.o+";\n"):l+=cb(n,v)([p],[],a)+" = "+k.o+";\n");"list"===g.type&&T(g,a);"list"===n.type&&T(n,a);return c?{code:l,o:p,type:n}:{code:l}}if("if$2"===b.oper||"if$3"===b.oper)return k=Z(a,b.args[0],!0),l=Z(a,b.args[1],c),f=e="",g=Y(a,b),c&&(f=B(),e+=R(g)+" "+f+";"),e+=k.code,e+="if("+k.o+") {\n",e+=l.code,c&&(e+=f+" = "+
X(a,l.o,l.type,g)+";\n"),"if$3"===b.oper&&(b=Z(a,b.args[2],c),e=e+"} else {\n"+b.code,c&&(e+=f+" = "+X(a,b.o,b.type,g)+";\n")),e+="}\n",c?{code:e,o:f,type:g}:{code:e};if("function"===b.ctype||"infix"===b.ctype){l=b.oper;if("verbatimglsl"===qa(l))return b=a.B.evaluateAndVal(b.args[0]).value,c?{o:b,type:z.ga,code:""}:{code:b};e=b.args.map(function(b){return Z(a,b,!0)});f=e.map(function(a){return a.type});if(a.l.hasOwnProperty(l)){k=Nb(a,l);g=Array(e.length);for(p=0;p<e.length;p++)g[p]=a.j[a.l[l].body.D[a.l[l].arglist[p].name]].w;
l=a.j[b.D[l]].w}else{l=qa(l);if("regional"===l)return c?{o:"",type:z.M,code:""}:{code:""};k=W[l](f);if(!k)return console.error("Could not find an implementation for "+l+"("+f.map(F).join(", ")+").\nReturning empty code"),c?{o:"",type:z.M,code:""}:{code:""};g=k.u;l=k.v;k=k.s}p="";n=Array(e.length);for(r=0;r<e.length;r++)p+=e[r].code,n[r]=X(a,e[r].o,f[r],g[r]);b=k(n,b.modifs,a);return c?{o:b,type:l,code:p}:{code:p+b+";\n"}}if("number"===b.ctype)return e=Y(a,b),b=db(b,y(b)),c?{o:b,type:e,code:""}:{code:e+
";\n"};if("string"===b.ctype)return console.error("Cannot compile strings to WebGL."),!1;if("variable"===b.ctype)return e=Y(a,b),f=b.name,f=b.D[f]||f,c?{o:f,type:e,code:""}:{code:f+";\n"};if("void"===b.ctype)return c?{o:"",type:z.M,code:""}:{code:""};if("field"===b.ctype)return e=Y(a,b),f=Z(a,b.obj,!0).o,f+="."+b.key,c?{o:f,type:e,code:""}:{code:f+";\n"};console.error("dont know how to this.compile "+JSON.stringify(b))}function Nb(a,b){Ob(a,b,a.l[b].arglist.length);return O(b.replace("$","_"))}
function Ob(a,b,c){if(!a.mark("compiledfunctions",b)){for(var e=a.l[b],f=b.replace("$","_"),g=e.body.D,k=Array(c),l=0;l<c;l++)k[l]=e.arglist[l].name;c=a.j[f].w===z.M;var p=R(a.j[f].w)+" "+f+"("+k.map(function(b){return R(a.j[g[b]].w)+" "+g[b]}).join(", ")+"){\n",n;for(n in e.j)k=e.j[n],p+=R(a.j[k].w)+" "+k+";\n";e=Z(a,e.body,!c);p+=e.code;c||(p+="return "+X(a,e.o,e.type,a.j[f].w)+";\n");p+="}\n";a.add("compiledfunctions",b,function(){return p})}}
function Ma(a,b){sa=0;b=oa(b);Ib(a,"cgl_pixel",!1);a.j.cgl_pixel.w=z.O;var c=b;a.K=!1;Mb(a,c);Kb(a,c);Lb(a,c);for(var e in a.A)c=a.B.evaluateAndVal(a.A[e].X),a.A[e].type=a.A[e].la?Qa(c):y(c);e=!0;for(var f in a.j)a.j[f].w=a.j[f].w||!1;for(;e;){e=!1;for(var g in a.j)for(var k in a.j[g].R){f=Wa(Y(a,a.j[g].R[k]));var l=c=a.j[g].w||!1;f&&(c?E(f,c)?l=c:l=A(c,f):l=f,l&&l!==c&&(a.j[g].w=l,e=!0))}}for(var p in a.A)"list"===a.A[p].type.type&&T(a.A[p].type,a);for(var n in a.j)"list"===a.j[n].w.type&&T(a.j[n].w,
a);a.K=!0;b=Z(a,b,!0);g=X(a,b.o,b.type,z.color);E(b.type,z.color)||console.error("expression does not generate a color");k=Hb(a,"structs");k+=Hb(a,"uniforms");p=[];for(var r in a.A)"constant"!=a.A[r].type.type&&a.A[r].type!=z.image&&p.push("uniform "+R(a.A[r].type)+" "+r+";");k+=p.join("\n");r="";for(var v in a.C)for(var H in a.C[v])r+=a.C[v][H].code+"\n";k=k+r+Hb(a,"includedfunctions");k+=Hb(a,"functions");for(var D in a.j)a.j[D].global&&(k+=R(a.j[D].w)+" "+D+";\n");k+=Hb(a,"compiledfunctions");
k+="void main(void) {\n"+b.code+"gl_FragColor = "+g+";\n}\n";console.log(k);v={};if(a.i.compiledfunctions)for(var fb in a.i.compiledfunctions.ea)v[fb]=a.B.getMyfunction(fb).generation;return{code:k,A:a.A,C:a.C,da:v}};function Pb(a,b,c,e){this.X=b;this.B=e;this.U=c;this.name=a;this.code="uniform sampler2D _sampler"+a+";\nuniform float _ratio"+a+";\nuniform vec2 _cropfact"+a+";\nuniform bool _repeat"+a+";\nuniform bool _mipmap"+a+";\nvec4 _imagergba"+a+" (vec2 A, vec2 B, vec2 p) {\n  p -= A; B -= A;\n  float b = dot(B,B);\n  p = vec2(dot(p,B),_ratio"+a+"*dot(p,vec2(-B.y,B.x)))/b;\n  if(_repeat"+a+") p = mod(p, vec2(1.));\n  if(_repeat"+a+" && _mipmap"+a+") {\n    vec4 color = vec4(0.);\n    float totalWeight = 0.;\n    for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {\n      vec2 delta = .5*vec2(dx, dy);\n      vec2 center = delta+vec2(.5);\n      vec2 tc = fract(p-delta)+delta;\n      float dst = dot(abs(tc-center),vec2(1.));\n      float w = max(.5-dst,0.);\n      w=w*w;\n      color += w * texture2D(_sampler"+
a+", tc*_cropfact"+a+");\n      totalWeight += w;\n    }\n    return color/totalWeight;\n  }\n  if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)\n    return texture2D(_sampler"+a+", p*_cropfact"+a+");\n  else\n    return vec4(0.);\n  }"}function Sa(a,b){var c=a.B.evaluateAndVal(a.X).value;a="string"===typeof c?a.B.getImage(c,!0):c;return null==a?(console.error("Could not find image "+c+"."),t):Fa(a,b)}
function Qb(a,b,c){c.C.hasOwnProperty(a)||(c.C[a]=[]);var e=c.C[a].length,f;for(f in c.C[a])if(e==c.C[a].length){var g=c.C[a][f].U,k=!0,l;for(l in["interpolation","mipmap","repeat"])k&&(pa(g,b)||(k=!1));k&&(e=f)}f=a+"_"+e;e==c.C[a].length&&c.C[a].push(new Pb(f,c.A[a].X,b,c.B));return f}function Gb(a,b,c){return["_imagergba",Qb(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}function Eb(a,b,c){return["(_imagergba",Qb(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}
function Fb(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["_imagergba",Qb(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],")"].join("")}function Db(a,b,c){c.add("uniforms","corners",function(){return"uniform vec2 _lowerleft, _lowerright;"});return["(_imagergba",Qb(a[0],b,c),"(_lowerleft, _lowerright, ",a[1],").rgb)"].join("")};function Rb(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Ua(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=Sb(a);if(!isNaN(c))return[c,c,c]}a=Rb(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return Sb(a)}):b}
function Ta(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function Sb(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function x(a){this.i=a}x.prototype.toString=function(){return this.i};
function Ia(a,b){var c=q;this.i=c.createProgram();this.W=Tb(this,c,c.VERTEX_SHADER,a);Tb(this,c,c.FRAGMENT_SHADER,b);a=this.i;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new x("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new x("Error validating shader:\n"+c.getProgramInfoLog(a));var e=this.i,f,g,k,l={},p,n,r,v;b=c.getProgramParameter(e,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(f=c.getActiveUniform(e,a))if(g=
f.name.replace(/\]/g,"")){for(p=l;k=/[.\[]/.exec(g);)n=g.substr(0,k.index),p.hasOwnProperty(n)?p=p[n]:"."===k[0]?p=p[n]={}:p=p[n]=[],g=g.substr(k.index+1);if(1<f.size){k=f.size;v=Array(k);for(n=0;n<k;++n)r=f.name+"["+n+"]",r=Ub(this,c,r,f),v[n]=r;p[g]=v}else r=Ub(this,c,f.name,f),p[g]=r}this.l=l}
function Tb(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new x("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.i,c);return c}
function Ub(a,b,c,e){a=b.getUniformLocation(a.i,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new x("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


