(function(){
'use strict';for(var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,da=["String","prototype","repeat"],ea=0;ea<da.length-1;ea++){var fa=da[ea];fa in ba||(ba[fa]={});ba=ba[fa]}
var ga=da[da.length-1],ha=ba[ga],ia=ha?ha:function(a){var b;if(null==this)throw new TypeError("The 'this' value for String.prototype.repeat must not be null or undefined");b=this+"";if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};ia!=ha&&null!=ia&&aa(ba,ga,{configurable:!0,writable:!0,value:ia});
var ja={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",
arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctan2vec2c:"vec2 arctan2vec2c(vec4 v){\nreturn arctan2c(v.xy,v.zw);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",
copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multc(a,vec2(b.x,-b.y));\n}\n",divcv:"vec4 divcv(vec4 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multcv(vec2(b.x,-b.y),a);\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",
green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",
logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(a.x*b.x-a.y*b.y+0.0000000000000001,a.y*b.x+a.x*b.y);\n}\n",multcv:"vec4 multcv(vec2 a,vec4 b){\nreturn vec4(a.x*b.x-a.y*b.y,a.y*b.x+a.x*b.y,\na.x*b.z-a.y*b.a,a.y*b.z+a.x*b.a);\n}\n",
negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",powi:"float powi(float a,int b){\nreturn pow(a,float(b));\n}\n",random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",
realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",
vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ka=!1,k,m,n,q,r={},u={},la=!1,ma,na=!1,oa=1,v={},w=[],pa=[];
function qa(){function a(c){k.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ka){k=document.createElement("canvas");k.id="glcanvas";k.style.display="none";k.width=k.height=0;document.body.appendChild(k);m=document.createElement("canvas");m.id="tmpcanvas";m.style.display="none";m.width=m.height=0;document.body.appendChild(m);var b="Unknown";k.addEventListener("webglcontextcreationerror",a,!1);(n=k.getContext("webgl"))||(n=k.getContext("experimental-webgl"));
if(!n)throw new ra("Could not obtain a WebGL context.\nReason: "+b);k.removeEventListener("webglcontextcreationerror",a,!1);na=n.getExtension("OES_texture_float")&&n.getExtension("OES_texture_float_linear");na||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(la=(ma=n.getExtension("OES_texture_half_float"))&&n.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));
navigator.userAgent.match(/(iPad|iPhone)/i)&&(console.log("You are  using an iPhone/iPad."),na=la=!1,n.getExtension("OES_texture_half_float")&&n.getExtension("OES_texture_half_float_linear")&&n.getExtension("EXT_color_buffer_half_float")?la=!0:console.error("Your browser does not suppert writing to half_float textures, we will use 8-bit textures."));ka=!0}};function sa(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,d=a.length;c<d;c++)b[c]=sa(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&(0<="oper impl args ctype stack name arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=sa(a[c])),a.modifs&&(b.modifs=a.modifs));return b}}
function ta(a,b){if(null==a||"object"!=typeof a)return a===b;if(a instanceof Array&&b instanceof Array){if(a.length!=b.length)return!1;for(var c=0,d=a.length;c<d;c++)if(!ta(a[c],b[c]))return!1;return!0}if(a instanceof Object&&b instanceof Object){c="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ");for(d=0;d<c.length;d++){var e=c[d];if(!ta(a[e],b[e]))return!1}return!0}return!1}function ua(a){return"number"===typeof a}
function va(a,b){if(a===b)return!0;if(ua(a)||ua(b))return a===b;for(var c in a)if(a.hasOwnProperty(c)&&(!b.hasOwnProperty(c)||!va(a[c],b[c])))return!1;for(var d in b)if(b.hasOwnProperty(d)&&!a.hasOwnProperty(d))return!1;return!0}function wa(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function xa(a){if("boolean"===a.ctype)return x;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?y:z:A;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=xa(b[0]),d=1;d<b.length;d++)c=ya(c,xa(b[d]));if(B(c,z)){if(2==b.length)return C;if(3==b.length)return D;if(4==b.length)return F}if(B(c,A)&&2==b.length)return G;if(c===C&&2==b.length)return H;if(c===G&&2==b.length)return za;if(c===D&&3==b.length)return Aa;if(c===F&&4==b.length)return Ba}}else if("string"===
a.ctype||"image"===a.ctype)return J;console.error("Cannot guess type of "+JSON.stringify(a));return q}var Ca=0;function Da(){Ca++;return"_helper"+Ca}function Ea(a,b){if(a>k.width||b>k.height)k.width=Math.ceil(a),k.height=Math.ceil(b)}function Fa(a,b,c){a=a.getInitialMatrix();b-=a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function Ga(a){return Fa(a,0,a.instance.canvas.clientHeight)}function Ha(a){return Fa(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}
var Ia=new Float32Array(1),Ja=new Int32Array(Ia.buffer);function Ka(a){Ia[0]=a;a=Ja[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function La(a){if(na)return new Float32Array(a);if(la){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Ka(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Ma(a){return na?new Float32Array(a):la?new Uint16Array(a):new Uint8Array(a)}function Na(){return na?n.FLOAT:la?ma.HALF_FLOAT_OES:n.UNSIGNED_BYTE}function Oa(a){for(var b=1;b<a;)b<<=1;return b};function Pa(a,b){a.hasOwnProperty("readcanvaswrappers")||(a.readcanvaswrappers=Array(4));var c=2*b.D+b.H;a.readcanvaswrappers.hasOwnProperty(c)||(a.writecanvaswrapper&&a.writecanvaswrapper.generation>a.generation&&a.writecanvaswrapper.L(),a.readcanvaswrappers[c]=new Qa(a,b),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.generation=Math.max(a.generation,a.readcanvaswrappers[c].generation+1)})));a.writecanvaswrapper&&(a.writecanvaswrapper=a.readcanvaswrappers[c]);
return a.readcanvaswrappers[c]}function Ra(a){if(!a.hasOwnProperty("writecanvaswrapper")){var b=-1;if(a.readcanvaswrappers)for(var c=3;0<=c;c--)a.readcanvaswrappers.hasOwnProperty(b)&&(b=c);else a.readcanvaswrappers=Array(4);-1==b&&(c={H:!0,D:!1,repeat:!1},b=2*c.D+c.H,a.readcanvaswrappers[b]=new Qa(a,c));a.writecanvaswrapper=a.readcanvaswrappers[b]}return a.writecanvaswrapper}
function Qa(a,b){this.canvas=a;this.h=b;this.w=a.width;this.s=a.height;Sa(this);this.o=0;this.i=[];this.C=[];this.generation=-1;this.bindTexture();a.drawTo=this.drawTo.bind(this);a.cdyUpdate=this.L.bind(this);a=Ma(this.G*this.B*4);for(var c=0;2>c;c++)this.i[c]=n.createTexture(),n.bindTexture(n.TEXTURE_2D,this.i[c]),n.pixelStorei(n.UNPACK_ALIGNMENT,1),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,this.G,this.B,0,n.RGBA,Na(),a),b.D?n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.H?n.LINEAR_MIPMAP_LINEAR:n.NEAREST_MIPMAP_LINEAR):
n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MIN_FILTER,b.H?n.LINEAR:n.NEAREST),n.texParameteri(n.TEXTURE_2D,n.TEXTURE_MAG_FILTER,b.H?n.LINEAR:n.NEAREST),this.C[c]=n.createFramebuffer(),n.bindFramebuffer(n.FRAMEBUFFER,this.C[c]),n.framebufferTexture2D(n.FRAMEBUFFER,n.COLOR_ATTACHMENT0,n.TEXTURE_2D,this.i[c],0);this.v=new Ta(ja.copytexture_v,ja.copytexture_f);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);a=n.getAttribLocation(this.v.h,"aPos");n.enableVertexAttribArray(a);
c=n.getAttribLocation(this.v.h,"aTexCoord");n.enableVertexAttribArray(c);var d=new Float32Array([0,0,1,0,0,1,1,1]),e=b.byteLength;n.bufferData(n.ARRAY_BUFFER,e+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,0,b);n.bufferSubData(n.ARRAY_BUFFER,e,d);n.vertexAttribPointer(a,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(c,2,n.FLOAT,!1,0,e)}function Sa(a){a.G=Oa(a.w+a.w/2*(a.h.D&&a.h.repeat));a.B=Oa(a.s+a.s/2*(a.h.D&&a.h.repeat))}Qa.prototype.bindTexture=function(){n.bindTexture(n.TEXTURE_2D,this.i[this.o])};
Qa.prototype.bindFramebuffer=function(){n.bindFramebuffer(n.FRAMEBUFFER,this.C[this.o^1]);this.o^=1};Qa.prototype.L=function(){var a;this.canvas.img.hasOwnProperty("getContext")?a=this.canvas.img.getContext("2d"):(this.canvas.img=document.createElement("canvas"),this.canvas.img.style.display="none",this.canvas.img.width=this.w,this.canvas.img.height=this.s,a=this.canvas.img.getContext("2d"));a.clearRect(0,0,this.w,this.s);this.drawTo(a,0,0);this.canvas.img.generation++};
Qa.prototype.drawTo=function(a,b,c){Ea(this.w,this.s);n.viewport(0,0,this.G,this.B);n.useProgram(this.v.h);n.activeTexture(n.TEXTURE0);n.bindTexture(n.TEXTURE_2D,this.i[this.o]);this.v.i.sampler([0]);n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();a.drawImage(k,0,k.height-this.s,this.w,this.s,b,c,this.w,this.s)};function Ua(a,b){this.l=a;this.o=b;Va(this)}
function Va(a){var b=Wa(new Xa(a.l),a.o);a.i=b.u;a.m=b.m;a.I=b.I;a.v=ja.standardFragmentHeader+b.code;a.C=ja.vshader;a.h=new Ta(a.C,a.v);b=n.createBuffer();n.bindBuffer(n.ARRAY_BUFFER,b);var b=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),c=n.getAttribLocation(a.h.h,"aPos");n.enableVertexAttribArray(c);a=n.getAttribLocation(a.h.h,"aTexCoord");n.enableVertexAttribArray(a);var d=new Float32Array([0,0,1,0,0,1,1,1]),e=b.byteLength;n.bufferData(n.ARRAY_BUFFER,e+d.byteLength,n.STATIC_DRAW);n.bufferSubData(n.ARRAY_BUFFER,
0,b);n.bufferSubData(n.ARRAY_BUFFER,e,d);n.vertexAttribPointer(c,3,n.FLOAT,!1,0,0);n.vertexAttribPointer(a,2,n.FLOAT,!1,0,e)}
function Ya(a){for(var b in a.i){var c=a.l.evaluateAndVal(a.i[b].A),d=a.i[b].type;if(!B(xa(c),d)){console.log("Type of "+b+" changed; forcing rebuild.");Va(a);n.useProgram(a.h.h);Ya(a);return}var e=a.h.i[b];if(void 0!==e)switch(d){case A:e([c.value.real,c.value.imag]);break;case x:c.value?e([1]):e([0]);break;case y:case z:e([c.value.real]);break;case C:case D:case F:var f=0;d===C&&(f=2);d===D&&(f=3);d===F&&(f=4);for(var d=[],h=0;h<f;h++)d.push(c.value[h].value.real);e(d);break;case H:case Aa:case Ba:f=
0;d===H&&(f=2);d===Aa&&(f=3);d===Ba&&(f=4);d=[];for(h=0;h<f;h++)for(var p=0;p<f;p++)d.push(c.value[p].value[h].value.real);e(d);break;case G:e([c.value[0].value.real,c.value[0].value.imag,c.value[1].value.real,c.value[1].value.imag]);break;case za:f=Array(16);for(d=0;2>d;d++)for(h=0;2>h;h++)p=c.value[d].value[h].value,f[8*h+2*d]=p.real,f[4*(2*h+1)+2*d+1]=p.real,f[4*(2*h+1)+2*d]=-p.imag,f[8*h+2*d+1]=p.imag;e(f);break;default:console.error("Don't know how to set uniform"+b+", which has the type "+K(d)+
", to "+c)}}a.h.i.hasOwnProperty("rnd_")&&a.h.i.rnd_([Math.random()])};CindyJS.registerPlugin(1,"CindyGL",function(a){function b(b,d,e,f,h,p){if(!b.R||b.P<oa)b.R=!0,b.P=oa,b.T=new Ua(a,b);b=b.T;var g;a:{for(g in b.I)if(b.l.getMyfunction(g).generation>b.I[g]){console.log(g+" is outdated; forcing rebuild.");g=!1;break a}g=!0}g||Va(b);var l=h/f;g=d.x+-(e.y-d.y)*l;l=d.y+(e.x-d.x)*l;Ea(f,h);p?n.viewport(0,0,f,h):n.viewport(0,k.height-h,f,h);n.useProgram(b.h.h);Ya(b);d=[e.x-d.x,g-d.x,d.x,e.y-d.y,l-d.y,d.y,0,0,1];b.h.i.hasOwnProperty("transformMatrix")&&b.h.i.transformMatrix([d[0],
d[3],d[6],d[1],d[4],d[7],d[2],d[5],d[8]]);d=0;for(var t in b.m)for(var E in b.m[t]){n.activeTexture(n.TEXTURE0+d);h=b.m[t][E];e=h.name;f={H:h.F.hasOwnProperty("interpolate")?h.l.evaluateAndVal(h.F.interpolate).value:!0,D:h.F.hasOwnProperty("mipmap")?h.l.evaluateAndVal(h.F.mipmap).value:!1,repeat:h.F.hasOwnProperty("repeat")?h.l.evaluateAndVal(h.F.repeat).value:!1};l=h;h=f;g=l.l.evaluateAndVal(l.A).value;l="string"===typeof g?l.l.getImage(g,!0):g;null==l?(console.error("Could not find image "+g+"."),
h=q):h=Pa(l,h);g=h;if(g.canvas.live||g.canvas.ready&&!(g.generation>=g.canvas.generation)){if(g.w!=g.canvas.width||g.s!=g.canvas.height){g.w=g.canvas.width;g.s=g.canvas.height;Sa(g);for(var l=Ma(g.G*g.B*4),I=0;2>I;I++)n.bindTexture(n.TEXTURE_2D,g.i[I]),n.texImage2D(n.TEXTURE_2D,0,n.RGBA,g.G,g.B,0,n.RGBA,Na(),l)}g.bindTexture();n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,1);g.h.repeat?(m.width=g.G,m.height=g.B,l=m.getContext("2d"),l.drawImage(g.canvas.img,0,g.B-g.s),l.drawImage(g.canvas.img,g.w,g.B-g.s),l.drawImage(g.canvas.img,
0,g.B-2*g.s),l.drawImage(g.canvas.img,g.w,g.B-2*g.s),n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Na(),m)):n.texSubImage2D(n.TEXTURE_2D,0,0,0,n.RGBA,Na(),g.canvas.img);g.h.D&&n.generateMipmap(n.TEXTURE_2D);n.pixelStorei(n.UNPACK_FLIP_Y_WEBGL,0);g.generation=g.canvas.generation;console.log("Image has been loaded to GPU")}h.bindTexture();b.h.i["_sampler"+e]([d]);b.h.i["_ratio"+e]([h.w/h.s]);b.h.i["_cropfact"+e]([h.w/h.G,h.s/h.B]);b.h.i["_repeat"+e]([f.repeat]);b.h.i["_mipmap"+e]([f.D]);d++}p?(p.bindFramebuffer(),
p.generation=++p.canvas.generation):n.bindFramebuffer(n.FRAMEBUFFER,null);n.drawArrays(n.TRIANGLE_STRIP,0,4);n.flush();p&&(p.generation=Math.max(p.generation,p.canvas.generation+1))}q=a.nada;a.defineFunction("compile",1,function(b){b=Wa(new Xa(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){oa++;return q});a.defineFunction("colorplot",1,function(c){qa();var d=a.instance.canvas.clientWidth,e=a.instance.canvas.clientHeight,f=a.instance.canvas.width,
h=a.instance.canvas.height;b(c[0],Ga(a),Ha(a),f,h,null);a.instance.canvas.getContext("2d").drawImage(k,0,0,f,h,0,0,d,e);return q});a.defineFunction("colorplot",3,function(c){qa();var d=c[0],e=a.extractPoint(a.evaluateAndVal(c[1])),f=a.extractPoint(a.evaluateAndVal(c[2])),h={x:Math.min(e.x,f.x),y:Math.min(e.y,f.y)},p={x:Math.max(e.x,f.x),y:Math.min(e.y,f.y)};c=a.instance.canvas.clientWidth;var g=a.instance.canvas.clientHeight,l=a.instance.canvas.width,t=a.instance.canvas.height,E=Fa(a,0,0),I=Ga(a),
ca=Ha(a),ca=Math.abs((e.x-f.x)/(I.x-ca.x)),E=Math.abs((e.y-f.y)/(E.y-I.y));b(d,h,p,l*ca,t*E,null);d=a.instance.canvas.getContext("2d");h=Math.min(e.x,f.x);e=Math.max(e.y,f.y);f=a.getInitialMatrix();d.drawImage(k,0,0,l*ca,t*E,h*f.a-e*f.b+f.tx,h*f.c-e*f.d-f.ty,ca*c,E*g);return q});a.defineFunction("colorplot",4,function(c){qa();var d=a.extractPoint(a.evaluateAndVal(c[0])),e=a.extractPoint(a.evaluateAndVal(c[1])),f=a.evaluateAndVal(c[2]);c=c[3];if(!d.ok||!e.ok||"string"!==f.ctype)return q;var f=a.getImage(f.value,
!0),h=Ra(f);b(c,d,e,f.width,f.height,h);return q});a.defineFunction("colorplot",2,function(c){qa();var d=Ga(a),e=Ha(a),f=a.evaluateAndVal(c[0]);c=c[1];if("string"!==f.ctype)return q;var f=a.getImage(f.value,!0),h=Ra(f);b(c,d,e,f.width,f.height,h);return q});a.defineFunction("setpixel",4,function(b){var d;var e=a.evaluateAndVal(b[0]),f;f=void 0===f?null:f;"string"===e.ctype?d=e.value:(console.log("argument is not a string"),d=f);e=Za(a.evaluateAndVal(b[1]));f=Za(a.evaluateAndVal(b[2]));b=$a(a.evaluateAndVal(b[3]));
if(!d)return q;var h=a.getImage(d,!0),h=Ra(h);isFinite(e)&&isFinite(f)&&d&&h&&b&&(h.bindTexture(),d=[b[0],b[1],b[2],1],n.texSubImage2D(n.TEXTURE_2D,0,e,f,1,1,n.RGBA,Na(),La(d)),b=h.canvas.img.getContext("2d"),h=b.createImageData(1,1),h.data.d=d,b.putImageData(h,e,f));return q})});function B(a,b){return a===b||a===ab?!0:ua(a)&&ua(b)?void 0===w[a]?!1:1073741824>w[a][b]:!1}var L=0;function ya(a,b){var c=void 0;if(B(b,a))return a;if(B(a,b)||!ua(a))return b;if(!ua(b))return a;for(var d=0;d<L;d++)B(a,d)&&B(b,d)&&(void 0===c?c=d:B(d,c)&&(c=d));return c}function bb(a){return{index:a,type:"template"}}var M={};
function cb(a,b){for(var c in M[a]){for(var d=M[a][c],e=b.length===d.f.length,f={},h=0;h<b.length&&e;h++)"template"===d.f[h].type?(void 0===f[d.f[h].index]&&(f[d.f[h].index]=[]),f[d.f[h].index].push(b[h])):e&=B(b[h],d.f[h]);if(e){var p={},g;for(g in f){p[g]=f[g][0];for(var l in f[g])p[g]=ya(p[g],f[g][l]),void 0===p[g]&&(e=!1)}if(e){a={f:[]};for(h=0;h<b.length&&e;h++)a.f[h]="template"===d.f[h].type?p[d.f[h].index]:d.f[h];a.g="template"===d.g.type?p[d.g.index]:d.g;return a}}}return q};var x=1,y=2,z=3,A=4,C=6,D=7,F=8,H=11,Aa=12,Ba=13,J=14,G=16,za=17,ab=18,db={V:x,Z:y,Y:z,W:A,ia:5,ea:C,ga:D,ha:F,color:9,da:10,$:H,ba:Aa,ca:Ba,image:J,X:15,fa:G,aa:za,U:ab};Object.freeze(db);function K(a){return"bool int float complex voidt float[2] float[3] float[4] color point float[2,2] float[3,3] float[4,4] image 2D-Coordinate complex[2] complex[2,2] anytype".split(" ")[a-1]}v[x]=[y];v[y]=[z];v[z]=[A,9];v[D]=[9,10];v[F]=[9];v[10]=[15];v[C]=[15,G];v[A]=[15];v[H]=[za];
var eb={f:[x],g:x},fb={f:[x,x],g:x},gb={f:[y],g:y},N={f:[y,y],g:y},hb={f:[],g:z},O={f:[z],g:z},P={f:[z,z],g:z},Q={f:[A],g:A},R={f:[A,A],g:A},ib={f:[C,C],g:C},jb={f:[G,G],g:G},kb={f:[D,D],g:D},lb={f:[F,F],g:F},mb={f:[z],g:A},S={f:[A],g:z},nb={f:[A,A],g:z},ob={f:[C],g:z},pb={f:[D],g:z},qb={f:[F],g:z},rb={f:[C,C],g:z},sb={f:[D,D],g:z},tb={f:[F,F],g:z},ub={f:[y,y],g:x},vb={f:[z,z],g:x},T=bb(1),wb=bb(2),xb=bb(3);M.sqrt=[mb,Q];M.abs=[O,S,ob,pb,qb];M.exp=[O,Q];M.log=[mb,Q];M.sin=[O,Q];M.cos=[O,Q];
M.tan=[O,Q];M.arccos=[mb,Q];M.arcsin=[mb,Q];M.arctan=[O,Q];M.arctan2=[P,R,S,{f:[C],g:z},{f:[G],g:A}];M.add=[N,P,R,ib,kb,lb,jb];M.sub=[N,P,R,ib,kb,lb,jb,{f:[5,y],g:y},{f:[5,z],g:z},{f:[5,A],g:A},{f:[5,C],g:C},{f:[5,D],g:D},{f:[5,F],g:F}];M.mult=[N,P];var yb=[A,C,D,F];yb.forEach(function(a){M.mult.push({f:[z,a],g:a});M.mult.push({f:[a,z],g:a})});M.mult=M.mult.concat([R,{f:[H,C],g:C},{f:[za,G],g:G},{f:[Aa,D],g:D},{f:[Ba,F],g:F}]);M.mult.push(rb);M.mult.push(sb);M.mult.push(tb);M.mult.push({f:[A,G],g:G});
M.mult.push({f:[G,A],g:G});M.div=[P,R];yb.forEach(function(a){M.div.push({f:[a,z],g:a})});M.div.push({f:[G,A],g:G});M.pow=[{f:[z,y],g:z},{f:[A,A],g:A}];M.re=[S];M.conjugate=[Q];M.im=[S];M.round=[{f:[z],g:y},{f:[A],g:A}];M.floor=[{f:[z],g:y},{f:[A],g:A}];M.ceil=[{f:[z],g:y},{f:[A],g:A}];M.mod=[N,P,R];M.random=[hb,O,Q];M.randominteger=[gb];M.randomint=[gb];M.seedrandom=[{f:[z],g:5}];M.randombool=[{f:[],g:x}];M.randomnormal=[{f:[],g:z}];M.dist=[P,nb,rb,sb,tb];
M._=[{f:[C,y],g:z},{f:[D,y],g:z},{f:[F,y],g:z},{f:[G,y],g:A}];M["^"]=M.pow;M["*"]=M.mult;M["/"]=M.div;M["+"]=M.add;M["-"]=M.sub;[">","<",">=","<=","=="].forEach(function(a){return M[a]=[ub,vb]});M["&"]=[fb];M["%"]=[fb];M["="]=[{f:[T,wb],g:wb}];M[";"]=[{f:[T,5],g:T},{f:[T,wb],g:wb},{f:[T],g:T}];M.abs_infix=M.abs;M.dist_infix=M.dist;M.not=[eb];M.and=[fb];M.or=[fb];M.xor=[fb];"red green blue gray grey hue".split(" ").forEach(function(a){return M[a]=[{f:[z],g:D}]});
M["if"]=[{f:[x,T,T],g:T},{f:[x,T,wb],g:5},{f:[x,T],g:T}];M.repeat=[{f:[y,T],g:T}];M.apply=[{f:[{type:"list",length:T,S:wb},{type:"expression",f:wb,g:xb}],g:{type:"list",length:T,S:xb}}];M.min=[N,P];M.max=[N,P];M.complex=[{f:[C],g:A}];M.re=[S];M.im=[S];M.genList=[{f:[z,z],g:C},{f:[z,z,z],g:D},{f:[z,z,z,z],g:F},{f:[A,A],g:G}];M.imagergb=[{f:[J,15],g:D},{f:[15,15,J,15],g:D}];M.imagergba=[{f:[J,15],g:F},{f:[15,15,J,15],g:F}];Object.freeze(M);for(var zb in db)var Ab=db[zb]+1,Bb=L,L=Bb>Ab?Bb:Ab;
for(var w=Array(L),pa=Array(L),Cb=0;Cb<L;Cb++){w[Cb]=Array(L);pa[Cb]=Array(L);for(var Db=0;Db<L;Db++)w[Cb][Db]=1073741824,pa[Cb][Db]=-1;w[Cb][Cb]=0}for(var Eb=0;Eb<L;Eb++)for(var Fb in v[Eb]){var Gb=v[Eb][Fb];w[Eb][Gb]=1;pa[Eb][Gb]=Gb}for(var Hb=0;Hb<L;Hb++)for(var Ib=0;Ib<L;Ib++)for(var Jb=0;Jb<L;Jb++)w[Ib][Hb]+w[Hb][Jb]<w[Ib][Jb]&&(w[Ib][Jb]=w[Ib][Hb]+w[Hb][Jb],pa[Ib][Jb]=pa[Ib][Hb]);Object.freeze(v);Object.freeze(w);Object.freeze(pa);var U={};function Kb(a,b,c){if(!c.M.hasOwnProperty(a)){c.M[a]=!0;for(var d in U[a])Kb(U[a][d],b,c);c.N.push(ja[a])}}function V(a){return function(b,c,d){Kb(a,c,d);return W(a)(b)}};function Xa(a){this.v={};this.o={};this.h={};this.u={};this.M={};this.N=[];this.C={};this.O=[];this.K=!1;this.i={};this.l=a;this.m={}}function Lb(a,b,c,d){if(!B(c,d))return console.error(K(c)+" is no subtype of "+K(d)+" (trying to cast the term "+b+")"),b;if(c===d||c===ab)return b;var e=pa[c][d];return X.hasOwnProperty(c)&&X[c].hasOwnProperty(e)?Lb(a,X[c][e](b,{},a),e,d):(console.error("CindyGL: No type-inclusion function for "+K(c)+" to "+K(e)+" found. \n Using identity"),Lb(a,b,e,d))}
function Mb(a,b,c){if(b.isuniform)return a.u[b.uvariable].type;if("variable"===b.ctype){b=b.name;if("#"===b)return C;if(a.h.hasOwnProperty(c)&&a.h[c].hasOwnProperty(b))return a.h[c][b];if(a.h.hasOwnProperty("")&&a.h[""].hasOwnProperty(b))return a.h[""][b]}else if("function"===b.ctype&&a.i.hasOwnProperty(b.oper)){if(a.h.hasOwnProperty("")&&a.h[""].hasOwnProperty(b.oper))return a.h[""][b.oper]}else{if("number"===b.ctype)return 0!==b.value.imag?A:(b.value.real|0)===b.value.real?y:z;if("void"===b.ctype)return 5;
if("field"===b.ctype)return z;if("string"===b.ctype)return J;for(var d=Array(b.args.length),e=0;e<b.args.length;e++)d[e]=Nb(a,b.args[e],c);a=cb(wa(b.oper),d);return void 0===a||a===q?q:a.g}return q}function Nb(a,b,c){a.K&&b.hasOwnProperty("computedType")||(b.computedType=Mb(a,b,c));return b.computedType}
function Ob(a,b){function c(a,b){d.hasOwnProperty(b)||(d[b]=[]);e.hasOwnProperty(b)||(e[b]={});for(var g in a.args)c(a.args[g],b);if("="===a.oper){var l=a.args[0].name;g=b;-1===d[b].indexOf(l)&&(g="",-1===d[g].indexOf(l)&&(d[g].push(l),e[g][l]=[]));e[g][l].push({A:a.args[1],J:b})}else if(void 0!==a.oper&&"regional"===wa(a.oper))for(l=0;l<a.args.length;l++)"variable"===a.args[l].ctype&&(g=a.args[l].name,-1===d[b].indexOf(g)&&(d[b].push(g),e[b][g]=[]));else if("function"===a.ctype&&f.hasOwnProperty(a.oper)){g=
a.oper;d.hasOwnProperty(g)||(d[g]=[]);e.hasOwnProperty(g)||(e[g]={});for(l in f[g].arglist){var t=f[g].arglist[l].name;d[g].push(t);e[g].hasOwnProperty(t)||(e[g][t]=[]);e[g][t].push({A:a.args[l],J:b})}c(f[g].body,g);-1===d[""].indexOf(g)&&(d[""].push(g),e[""][g]=[{A:f[g].body,J:g}])}}var d={},e={},f=a.i;c(b,"");a.v=d;a.o=e}
function Pb(a,b){function c(a,b){if(a.hasOwnProperty("dependsOnPixel")&&!0===a.dependsOnPixel)return!0;if("variable"===a.ctype){var d=a.name;return e.hasOwnProperty(b)&&e[b][d]||-1===f[b].indexOf(d)&&e.hasOwnProperty("")&&e[""][d]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}d=["random","verbatimglsl"];if("function"===a.ctype&&-1!=d.indexOf(wa(a.oper)))return a.dependsOnPixel=!0;for(var g in a.args)if(c(a.args[g],b))return a.dependsOnPixel=!0;return"function"===a.ctype&&h.hasOwnProperty(a.oper)&&(d=a.oper,
e.hasOwnProperty(d)||(e[d]={}),c(h[d].body,d))?a.dependsOnPixel=!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj,b):!1}function d(a,b){if(c(a,b)){for(var e in a.args)d(a.args[e],b);"field"===a.ctype&&d(a.obj,b);"function"===a.ctype&&h.hasOwnProperty(a.oper)&&(a=a.oper,l.hasOwnProperty(a)||(l[a]=!0,d(h[a].body,a)))}else if("number"!==a.ctype&&"void"!==a.ctype){b=!1;var f,g;for(g in t)!b&&ta(a,t[g].A)&&(b=!0,f=g);b||(f=Da(),t[f]={A:a,type:q});a.isuniform=!0;a.uvariable=f}}var e={"":{"#":!0}},f=a.v,h=a.i,
p;for(p in a.o)for(var g in a.o[p])e.hasOwnProperty(p)||(e[p]={}),e[p][g]=!0;c(b,"");var l={"":!0},t={};d(b,"");a.u=t}function Qb(a,b){if("function"===b.ctype&&!a.i.hasOwnProperty(b.oper)&&null!==a.l.getMyfunction(b.oper)){var c=b.oper;a.i[c]=sa(a.l.getMyfunction(c));Qb(a,a.i[c].body)}for(var d in b.args)Qb(a,b.args[d])}
function Y(a,b,c,d){if(b.isuniform){b=b.uvariable;var e=a.u[b].type;return d?{code:"",j:b,type:e}:{code:""}}if(";"===b.oper){for(var e={type:5,j:""},f="",h=b.args.length-1,p=h;0<=p;p--)"void"===b.args[p].ctype&&h--;for(p=0;p<=h;p++)e=Y(a,b.args[p],c,d&&p===h),f+=e.code;return d?{code:f,j:e.j,type:e.type}:{code:f}}if("="===b.oper)return e=Y(a,b.args[1],c,!0),f=b.args[0].name,b=f+" = "+Lb(a,e.j,e.type,Nb(a,b.args[0],c)),d?{code:e.code,j:b,type:a.h[c][f]}:{code:e.code+b+";\n"};if("repeat$2"===b.oper){if("number"!==
b.args[0].ctype)return console.error("repeat possible only for fixed constant number in GLSL"),q;e=Da();f=b.args[0].value.real|0;b=Y(a,b.args[1],c,d);p=h="";d&&(p=Da(),h+=r[b.type]+" "+p+";");h=h+("for(int "+e+"=0; "+e+" < "+f+"; "+e+"++) {\n")+b.code;d&&(h+=p+" = "+b.j+";\n");h+="}\n";return d?{code:h,j:p,type:b.type}:{code:h}}if("repeat$3"===b.oper)console.error("TODO");else{if("if$2"===b.oper||"if$3"===b.oper){var p=Y(a,b.args[0],c,!0),g=Y(a,b.args[1],c,d),f=e="",h=Nb(a,b,c);d&&(f=Da(),e+=r[h]+
" "+f+";");e+=p.code;e+="if("+p.j+") {\n";e+=g.code;d&&(e+=f+" = "+Lb(a,g.j,g.type,h)+";\n");"if$3"===b.oper&&(b=Y(a,b.args[2],c,d),e=e+"} else {\n"+b.code,d&&(e+=f+" = "+Lb(a,b.j,b.type,h)+";\n"));e+="}\n";return d?{code:e,j:f,type:h}:{code:e}}if("function"===b.ctype||"infix"===b.ctype){var l=b.oper;if("verbatimglsl"===wa(l))return b=a.l.evaluateAndVal(b.args[0]).value,d?{j:b,type:ab,code:""}:{code:b};e=b.args.map(function(b){return Y(a,b,c,!0)});h=e.map(function(a){return a.type});if(a.i.hasOwnProperty(l)){f=
Rb(a,l);p=Array(e.length);for(g=0;g<e.length;g++)p[g]=a.h[l][a.i[l].arglist[g].name];g=a.h[""][l]}else{l=wa(l);if("regional"===l)return d?{j:"",type:5,code:""}:{code:""};var t=cb(l,h);if(t===q)return console.error("Could not find a signature for "+l+"("+h.map(K).join(", ")+").\nReturning empty code"),d?{j:"",type:5,code:""}:{code:""};var p=t.f,g=t.g,f=q,E;for(E in u[l])if(va(u[l][E][0],t)){f=u[l][E][1];break}f===q&&(console.error("There is no webgl-implementation for "+l+"("+t.f.map(K).join(", ")+
").\ndefault: Try glsl-function with same name"),f=function(a){return l+"("+a.join(", ")+")"})}E="";for(var t=Array(e.length),I=0;I<e.length;I++)E+=e[I].code,t[I]=Lb(a,e[I].j,h[I],p[I]);b=f(t,b.modifs,a);return d?{j:b,type:g,code:E}:{code:E+b+";\n"}}if("number"===b.ctype)return f=Nb(a,b,c),f===y?e=b.value.real|0:f===z?e=b.value.real:f===A&&(e="vec2( "+b.value.real+", "+b.value.imag+")"),d?{j:e,type:f,code:""}:{code:f+";\n"};if("string"===b.ctype)return console.error("Cannot compile strings to WebGL."),
q;if("variable"===b.ctype)return e=Nb(a,b,c),b=b.name,"#"===b&&(b="cgl_pixel"),d?{j:b,type:e,code:""}:{code:b+";\n"};if("void"===b.ctype)return d?{j:"",type:5,code:""}:{code:""};if("field"===b.ctype)return e=Nb(a,b,c),f=Y(a,b.obj,c,!0).j,f+="."+b.key,d?{j:f,type:e,code:""}:{code:f+";\n"}}console.error("dont know how to this.compile "+JSON.stringify(b))}function Rb(a,b){Sb(a,b,a.i[b].arglist.length);return W(b)}
function Sb(a,b,c){if(!a.C.hasOwnProperty(b)){a.C[b]=!0;for(var d=a.i[b],e=Array(c),f=0;f<c;f++)e[f]=d.arglist[f].name;c=5===r[a.h[""][b]];var f=r[a.h[""][b]]+" "+wa(b)+"("+e.map(function(c){return r[a.h[b][c]]+" "+c}).join(", ")+"){\n",h;for(h in a.v[b]){for(var p=!0,g=a.v[b][h],l=0;l<e.length;l++)p&=g!==e[l];p&&(f+=r[a.h[b][g]]+" "+g+";\n")}d=Y(a,d.body,b,!c);f+=d.code;c||(f+="return "+Lb(a,d.j,d.type,a.h[""][b])+";\n");a.O.push(f+"}\n")}}
function Wa(a,b){Ca=0;var c=b=sa(b);a.K=!1;Qb(a,c);Ob(a,c);Pb(a,c);for(var d in a.u)a.u[d].type=z,c=a.l.evaluateAndVal(a.u[d].A),a.u[d].type=xa(c),console.log("guessed type "+K(a.u[d].type)+" for "+JSON.stringify(a.u[d].A.name));for(d=!0;d;){d=!1;for(var e in a.o)for(var f in a.o[e])for(var h in a.o[e][f]){var c=Nb(a,a.o[e][f][h].A,a.o[e][f][h].J),p=q;a.h.hasOwnProperty(e)&&a.h[e].hasOwnProperty(f)&&(p=a.h[e][f]);var g;c!==q&&(g=p===q?c:B(c,p)?p:ya(p,c),g!==q&&g!==p&&(a.h.hasOwnProperty(e)||(a.h[e]=
{}),a.h[e][f]=g,console.log("variable "+f+" in scope "+e+" got type "+K(g)+" (oltype/othertype is "+K(p)+"/"+K(c)+")"),d=!0))}}a.K=!0;b=Y(a,b,"",!0);e=Lb(a,b.j,b.type,9);B(b.type,9)||console.error("expression does not generate a color");var l;f=[];for(l in a.u)a.u[l].type!=J&&f.push("uniform "+r[a.u[l].type]+" "+l+";");l=f.join("\n");f="";for(var t in a.m)for(var E in a.m[t])f+=a.m[t][E].code+"\n";l=l+f+a.N.join("\n");for(var I in a.v[""])t=a.v[""][I],a.i.hasOwnProperty(t)||(l+=r[a.h[""][t]]+" "+
t+";\n");l+=a.O.join("\n");l+="void main(void) {\n"+b.code+"gl_FragColor = "+e+";\n}\n";console.log(l);I={};for(var ca in a.C)I[ca]=a.l.getMyfunction(ca).generation;return{code:l,u:a.u,m:a.m,I:I}};function Tb(a,b,c,d){this.A=b;this.l=d;this.F=c;this.name=a;this.code=["uniform sampler2D _sampler",a,";uniform float _ratio",a,";uniform vec2 _cropfact",a,";uniform bool _repeat",a,";uniform bool _mipmap",a,";vec4 _imagergba",a,"(vec2 A, vec2 B, vec2 p) {p -= A; B -= A;float b = dot(B,B);p = vec2(dot(p,B),_ratio",a,"*dot(p,vec2(-B.y,B.x)))/b;if(_repeat",a,") p = mod(p, vec2(1.));if(_repeat",a," && _mipmap",a,") {vec4 color = vec4(0.);float totalWeight = 0.;for(int dx=0; dx<2; dx++) for(int dy=0; dy<2; dy++) {vec2 delta = .5*vec2(dx, dy);vec2 center = delta+vec2(.5);vec2 tc = fract(p-delta)+delta;float dst = dot(abs(tc-center),vec2(1.));float w = max(.5-dst,0.);w=w*w;color += w * texture2D(_sampler",
a,", tc*_cropfact",a,");totalWeight += w;}return color/totalWeight;}if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)return texture2D(_sampler",a,", p*_cropfact",a,");else return vec4(0.);}"].join("")}function Ub(a,b,c){c.m.hasOwnProperty(a)||(c.m[a]=[]);var d=c.m[a].length,e;for(e in c.m[a])if(d==c.m[a].length){var f=c.m[a][e].F,h=!0,p;for(p in["interpolation","mipmap","repeat"])h&&(ta(f,b)||(h=!1));h&&(d=e)}e=a+"_"+d;d==c.m[a].length&&c.m[a].push(new Tb(e,c.u[a].A,b,c.l));return e};r[x]="bool";r[y]="int";r[z]="float";r[A]="vec2";r[5]="void";r[C]="vec2";r[D]="vec3";r[F]="vec4";r[H]="mat2";r[Aa]="mat3";r[Ba]="mat4";r[9]="vec4";r[10]="vec3";r[15]="vec2";r[G]="vec4";r[za]="mat4";Object.freeze(r);function W(a){return function(b){return wa(a)+"("+b+")"}}function Z(a){return function(b){return"("+b.join(a)+")"}}function Vb(a){return a}var X={},Wb;for(Wb in db)X[db[Wb]]={};X[x][y]=W("int");X[y][z]=W("float");X[z][A]=function(a){return"vec2("+a+", 0.)"};X[z][9]=V("float2color");
X[9][D]=function(a){return"("+a+").rgb"};X[9][F]=Vb;X[C][10]=function(a){return"vec3("+a+",1.0)"};X[D][9]=function(a){return"vec4("+a+",1.0)"};X[D][10]=Vb;X[F][9]=Vb;X[10][C]=V("dehomogenize");X[10][D]=Vb;X[10][15]=V("dehomogenize");X[C][15]=Vb;X[A][15]=Vb;X[C][G]=V("vec2complex");X[H][za]=V("mat2complex");Object.freeze(X);u.sqrt=[[mb,V("sqrtf")],[Q,V("sqrtc")]];u.abs=[[O,W("abs")],[S,W("length")],[ob,W("length")],[pb,W("length")],[qb,W("length")]];u.abs_infix=u.abs;
u.dist=[[P,function(a){return W("abs")(Z("-")(a))}],[nb,function(a){return W("length")(Z("-")(a))}],[rb,function(a){return W("length")(Z("-")(a))}],[sb,function(a){return W("length")(Z("-")(a))}],[tb,function(a){return W("length")(Z("-")(a))}]];u.dist_infix=u.dist;u.sin=[[O,W("sin")],[Q,V("sinc")]];u.cos=[[O,W("cos")],[Q,V("cosc")]];u.tan=[[O,W("tan")],[Q,V("tanc")]];u.exp=[[O,W("exp")],[Q,V("expc")]];u.arctan=[[O,W("atan")],[Q,V("arctanc")]];u.log=[[mb,V("logr")],[Q,V("logc")]];u.add=[];u.sub=[];
[N,P,R,ib,kb,lb,jb].forEach(function(a){u.add.push([a,Z("+")]);u.sub.push([a,Z("-")])});function Xb(a){return"-("+a[1]+")"}[y,z,A,C,D,F].forEach(function(a){u.sub.push([{f:[5,a],g:a},Xb])});function Yb(a){return isFinite(a[1])?"("+a[0]+")["+(a[1]-1)+"]":"("+a[0]+")["+a[1]+"-1]"}
u._=[[{f:[C,y],g:z},Yb],[{f:[D,y],g:z},Yb],[{f:[F,y],g:z},Yb],[{f:[G,y],g:A},function(a){if(1===a[1])return"("+a[0]+").xy";if(2===a[1])return"("+a[0]+").zw";console.error("access of components of complex[2] only works for indeces that were hardcoded in CindyJS");return"ERROR: SEE CONSOLE (index was "+a[1]+") \n"}]];u["+"]=u.add;u["-"]=u.sub;
u.mult=[[N,Z("*")],[P,Z("*")],[R,V("multc")],[{f:[H,C],g:C},Z("*")],[{f:[za,G],g:G},Z("*")],[{f:[Aa,D],g:D},Z("*")],[{f:[Ba,F],g:F},Z("*")],[rb,W("dot")],[sb,W("dot")],[tb,W("dot")]];yb.forEach(function(a){u.mult.push([{f:[z,a],g:a},Z("*")]);u.mult.push([{f:[a,z],g:a},Z("*")])});u.mult.push([{f:[A,G],g:G},V("multcv")]);u.mult.push([{f:[G,A],g:G},function(a){return V("multcv")([a[1],a[0]])}]);u["*"]=u.mult;u.div=[[P,Z("/")],[R,V("divc")]];yb.forEach(function(a){u.div.push([{f:[a,z],g:a},Z("/")])});
u.div.push([{f:[G,A],g:G},V("divcv")]);u["/"]=u.div;u.re=[[S,V("realc")]];u.im=[[S,V("imagc")]];u.floor=[[{f:[z],g:y},function(a){return"int(floor("+a+"))"}],[{f:[A],g:A},W("floor")]];u.round=[[{f:[z],g:y},function(a){return"int(floor("+a+"+.5))"}],[{f:[A],g:A},function(a){return"floor("+a+"+vec2(.5))"}]];u.ceil=[[{f:[z],g:y},function(a){return"int(ceil("+a+"))"}],[{f:[A],g:A},W("ceil")]];u.mod=[[N,function(a,b){return"int("+W("mod")("float("+a[0]+"), float("+a[1]+")",b)+")"}],[P,W("mod")],[R,W("mod")]];
u.random=[[hb,V("random")],[O,function(a,b){return V("random")([],b)+"*"+a[0]}],[Q,function(a,b){return"vec2("+V("random")([],b)+","+V("random")([],b)+")*"+a[0]}]];u.arctan2=[[P,function(a){return"atan("+a[1]+", "+a[0]+")"}],[R,V("arctan2c")],[S,V("arctan2vec2")],[{f:[C],g:z},V("arctan2vec2")],[{f:[G],g:A},V("arctan2vec2c")]];["red","green","blue","gray","hue"].forEach(function(a){return u[a]=[[{f:[z],g:D},V(a)]]});u.grey=u.gray;u.min=[[N,W("min")],[P,W("min")]];u.max=[[N,W("max")],[P,W("max")]];
u.complex=[[{f:[C],g:A},Vb]];u.pow=[[{f:[z,y],g:z},function(a){return"pow("+a[0]+", float("+a[1]+"))"}],[{f:[A,A],g:A},V("powc")]];u["^"]=u.pow;u.re=[[S,function(a){return"("+a+").x"}]];u.conjugate=[[Q,V("conjugate")]];u.im=[[S,function(a){return"("+a+").y"}]];u.genList=[[{f:[z,z],g:C},W("vec2")],[{f:[z,z,z],g:D},W("vec3")],[{f:[z,z,z,z],g:F},W("vec4")],[{f:[A,A],g:G},W("vec4")]];u["&"]=[[fb,Z("&&")]];u["%"]=[[fb,Z("||")]];[">","<",">=","<=","=="].forEach(function(a){return u[a]=[[ub,Z(a)],[vb,Z(a)]]});
u.imagergb=[[{f:[J,15],g:D},function(a,b,c){var d=Ga(c.l),e=Ha(c.l);return["(_imagergba",Ub(a[0],b,c),"(vec2(",d.x,",",d.y,"),vec2(",e.x,",",e.y,"), ",a[1],").rgb)"].join("")}],[{f:[15,15,J,15],g:D},function(a,b,c){return["(_imagergba",Ub(a[2],b,c),"(",a[0],",",a[1],",",a[3],").rgb)"].join("")}]];
u.imagergba=[[{f:[J,15],g:F},function(a,b,c){var d=Ga(c.l),e=Ha(c.l);return["_imagergba",Ub(a[0],b,c),"(vec2(",d.x,",",d.y,"),vec2(",e.x,",",e.y,"), ",a[1],")"].join("")}],[{f:[15,15,J,15],g:F},function(a,b,c){return["_imagergba",Ub(a[2],b,c),"(",a[0],",",a[1],",",a[3],")"].join("")}]];Object.freeze(u);U.divc=["multc"];U.divcv=["multcv"];U.powc=["expc","multc","logc"];U.sqrtc=["expc","multc","logc"];U.arccosc=["multc","negc","sqrtc","addc","logc"];U.arcsinc=["multc","negc","sqrtc","addc","logc"];
U.tanc=["sinc","cosc","divc"];U.arctanc=["logc","addc","multc","subc"];U.arctan2c=["logc","divc","sqrtc","multc"];U.arctan2vec2c=["arctan2c"];U.hue=["hsv2rgb"];Object.freeze(U);function Zb(a){var b;b=b?b:null;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function $a(a){var b;b=b?b:[.5,.5,.5];if("number"===a.ctype){var c=$b(a);if(!isNaN(c))return[c,c,c]}a=Zb(a);return a?3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return $b(a)}):b}
function Za(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function $b(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function ra(a){this.h=a}ra.prototype.toString=function(){return this.h};
function Ta(a,b){var c=n;this.h=c.createProgram();ac(this,c,c.VERTEX_SHADER,a);ac(this,c,c.FRAGMENT_SHADER,b);a=this.h;c.linkProgram(a);if(!c.getProgramParameter(a,c.LINK_STATUS))throw new ra("Error linking shader:\n"+c.getProgramInfoLog(a));c.validateProgram(a);if(!c.getProgramParameter(a,c.VALIDATE_STATUS))throw new ra("Error validating shader:\n"+c.getProgramInfoLog(a));var d=this.h,e,f,h,p={},g,l,t,E;b=c.getProgramParameter(d,c.ACTIVE_UNIFORMS);for(a=0;a<b;++a)if(e=c.getActiveUniform(d,a))if(f=
e.name.replace(/\]/g,"")){for(g=p;h=/[.\[]/.exec(f);)l=f.substr(0,h.index),g.hasOwnProperty(l)?g=g[l]:"."===h[0]?g=g[l]={}:g=g[l]=[],f=f.substr(h.index+1);if(1<e.size){h=e.size;E=Array(h);for(l=0;l<h;++l)t=e.name+"["+l+"]",t=bc(this,c,t,e),E[l]=t;g[f]=E}else t=bc(this,c,e.name,e),g[f]=t}this.i=p}
function ac(a,b,c,d){c=b.createShader(c);b.shaderSource(c,d);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(d.split("\n")),new ra("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.h,c)}
function bc(a,b,c,d){a=b.getUniformLocation(a.h,c);switch(d.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new ra("Unknown data type for uniform "+c);}};
}).call(this);//# sourceMappingURL=CindyGL.js.map


