(function(){
'use strict';var aa={addc:"vec2 addc(vec2 a,vec2 b){\nreturn a+b;\n}\n",arccosc:"vec2 arccosc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=addc(multc(logc(tmp1),vec2(0.0,1.0)),vec2(pi*0.5,0.0));\nreturn erg;\n}\n",arcsinc:"vec2 arcsinc(vec2 a){\nvec2 t2=multc(a,negc(a));\nvec2 tmp=sqrtc(addc(vec2(1.0,0.0),t2));\nvec2 tmp1=addc(multc(a,vec2(0.0,1.0)),tmp);\nvec2 erg=multc(logc(tmp1),vec2(0.0,-1.0));\nreturn erg;\n}\n",
arctan2c:"\n\n\n\nvec2 arctan2c(vec2 x,vec2 y){\nvec2 r=logc(divc(x+vec2(-y.y,y.x),sqrtc(multc(x,x)+multc(y,y))));\nreturn vec2(r.y, -r.x);\n}\n",arctan2vec2:"float arctan2vec2(vec2 v){\nreturn atan(v.y,v.x);\n}\n",arctan2vec2c:"vec2 arctan2vec2c(vec4 v){\nreturn arctan2c(v.xy,v.zw);\n}\n",arctanc:"vec2 arctanc(vec2 a){\nvec2 t1=logc(addc(multc(a,vec2(0.0,-1.0)),vec2(1.0,0.0)));\nvec2 t2=logc(addc(multc(a,vec2(0.0,1.0)),vec2(1.0,0.0)));\nvec2 erg=multc(subc(t1,t2),vec2(0.0,0.5));\nreturn erg;\n}\n",
blue:"vec3 blue(float f)\n{\nreturn vec3(0.,0.,clamp(f,0.,1.));\n}\n",cimag:"float imagc(vec2 a){\nreturn a.y;\n}\n",conjugate:"vec2 conjugate(vec2 a){\nreturn vec2(a.x, -a.y);\n}\n",copytexture_f:"#ifdef GL_ES\nprecision highp float;\n#endif\n\nuniform sampler2D sampler;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_FragColor=texture2D(sampler,cgl_pixel);\n}\n",copytexture_v:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\n\nvoid main(void){\ngl_Position=vec4(aPos,1.);\ncgl_pixel=aTexCoord;\n}\n",
cosc:"vec2 cosc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat i= (imag1+imag2) /2.0;\nfloat r= (real1+real2) /2.0;\n\nreturn vec2(r,i);\n}\n",creal:"float realc(vec2 a){\nreturn a.x;\n}\n",dehomogenize:"vec2 dehomogenize(vec3 z){\nreturn vec2(z.x,z.y)/z.z;\n}\n",divc:"vec2 divc(vec2 a,vec2 b){\nreturn 1./(b.x*b.x+b.y*b.y)*multc(a,vec2(b.x,-b.y));\n}\n",expc:"vec2 expc(vec2 a){\nfloat n=exp(a.x);\nfloat r=n*cos(a.y);\nfloat i=n*sin(a.y);\nreturn vec2(r,i);\n}\n",
float2color:"vec4 float2color(float f)\n{\nreturn vec4(f,f,f,1.);\n}\n",gray:"vec3 gray(float f)\n{\nf=clamp(f,0.,1.);\nreturn vec3(f,f,f);\n}\n",green:"vec3 green(float f)\n{\nreturn vec3(0.,clamp(f,0.,1.),0.);\n}\n",hsv2rgb:"vec3 hsv2rgb(vec3 c)\n{\nvec4 K=vec4(1.0,2.0/3.0,1.0/3.0,3.0);\nvec3 p=abs(fract(c.xxx+K.xyz) *6.0-K.www);\nreturn c.z*mix(K.xxx,clamp(p-K.xxx,0.0,1.0),c.y);\n}\n",hue:"vec3 hue(float a){\nreturn hsv2rgb(vec3(a,1.,1.));\n}\n",imagc:"float imagc(vec2 a){\nreturn a.y;\n}\n",invc:"vec2 invc(vec2 a){\nfloat n=a.x*a.x+a.y*a.y;\nreturn vec2(a.x/n,-a.y/n);\n}\n",
logc:"vec2 logc(vec2 a){\nfloat re=a.x;\nfloat im=a.y;\nfloat s=sqrt(re*re+im*im);\nfloat i=im;\nfloat imag=atan(im,re);\nif(i<0.0){\nimag+= (2.0*pi);\n}\nif(i==0.0&&re<0.0){\nimag=pi;\n}\nif(imag>pi){\nimag-= (2.0*pi);\n};\nfloat real=log(s);\n\nreturn vec2(real,imag);\n}\n",logr:"vec2 logr(float a){\nif(a>=0.)return vec2(log(a),0);\nelse return vec2(log(-a),pi);\n}\n",mat2complex:"mat4 mat2complex(mat2 a)\n{\nreturn mat4(\nvec4(a[0][0],0,a[0][1],0),\nvec4(0,a[0][0],0,a[0][1]),\nvec4(a[1][0],0,a[1][1],0),\nvec4(0,a[1][0],0,a[1][1])\n);\n}\n",
multc:"vec2 multc(vec2 a,vec2 b){\nreturn vec2(a.x*b.x-a.y*b.y+0.0000000000000001,a.y*b.x+a.x*b.y);\n}\n",negc:"vec2 negc(vec2 a){\nreturn vec2(-a.x,-a.y);\n}\n",powc:"vec2 powc(vec2 a,vec2 b){\nreturn expc(multc(logc(a),b));\n}\n",powi:"float powi(float a,int b){\nreturn pow(a,float(b));\n}\n",random:"uniform float rnd_;\n\nfloat last_rnd= .1231;\nfloat random(){\nfloat a=mod(rnd_*plain_pixel.x*32.23,1.21);\nfloat b=mod(last_rnd*plain_pixel.y*54.21,1.32);\nlast_rnd=mod(a+b+12232.2213*(1.+rnd_)*dot(plain_pixel,plain_pixel)+a+sin(b)+b*sin(dot(plain_pixel,vec2(232.121+rnd_,2232.11))+last_rnd*121.11)*129.12+rnd_,1.);\nreturn last_rnd;\n\n\n}\n",
realc:"float realc(vec2 a){\nreturn a.x;\n}\n",red:"vec3 red(float f)\n{\nreturn vec3(clamp(f,0.,1.),0.,0.);\n}\n",rgb2hsv:"vec3 rgb2hsv(vec3 c)\n{\nvec4 K=vec4(0.0, -1.0/3.0,2.0/3.0, -1.0);\nvec4 p=mix(vec4(c.bg,K.wz),vec4(c.gb,K.xy),step(c.b,c.g));\nvec4 q=mix(vec4(p.xyw,c.r),vec4(c.r,p.yzx),step(p.x,c.r));\n\nfloat d=q.x-min(q.w,q.y);\nfloat e=1.0e-10;\nreturn vec3(abs(q.z+ (q.w-q.y) / (6.0*d+e)),d/ (q.x+e),q.x);\n}\n",sinc:"\n\nvec2 sinc(vec2 a){\n\nfloat n=exp(a.y);\nfloat imag1=n*sin(-a.x);\nfloat real1=n*cos(-a.x);\nn=exp(-a.y);\nfloat imag2=n*sin(a.x);\nfloat real2=n*cos(a.x);\nfloat r= -(imag1-imag2) /2.0;\nfloat i= (real1-real2) /2.0;\n\nreturn vec2(r,i);\n}\n",
sqrtc:"vec2 sqrtc(vec2 a){\nreturn expc(multc(logc(a),vec2(0.5,0.0)));\n}\n",sqrtf:"vec2 sqrtf(float a){\nif(a>=0.)return vec2(sqrt(a),0.);\nelse return vec2(0.,sqrt(-a));\n}\n",standardFragmentHeader:"#ifdef GL_ES\nprecision highp float;\n#endif\n\n#define pi 3.141592653589793\n\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\n",subc:"vec2 subc(vec2 a,vec2 b){\nreturn a-b;\n}\n",tanc:"vec2 tanc(vec2 a){\nvec2 s=sinc(a);\nvec2 c=cosc(a);\nreturn divc(s,c);\n}\n",vec2complex:"vec4 vec2complex(vec2 a)\n{\nreturn vec4(a.x,0.,a.y,0);\n}\n",
vshader:"attribute vec3 aPos;\nattribute vec2 aTexCoord;\nvarying vec2 cgl_pixel;\nvarying vec2 plain_pixel;\nuniform mat3 transformMatrix;\nvoid main(void){\ngl_Position=vec4(aPos,1.);\nplain_pixel=aTexCoord;\nvec3 r=transformMatrix*vec3(plain_pixel,1);\ncgl_pixel=r.xy/r.z;\n}\n"};var ba=!1,g,l,ca=[],n,q={},r={},da=!1,ea,fa=!1,ga=1,t={},u=[],ha=[];
function ia(){function a(c){g.removeEventListener("webglcontextcreationerror",a,!1);c.statusMessage&&(b=c.statusMessage)}if(!ba){g=document.createElement("canvas");g.id="glcanvas";g.style.display="none";g.width=g.height=0;document.body.appendChild(g);var b="Unknown";g.addEventListener("webglcontextcreationerror",a,!1);(l=g.getContext("webgl"))||(l=g.getContext("experimental-webgl"));if(!l)throw new ja("Could not obtain a WebGL context.\nReason: "+b);g.removeEventListener("webglcontextcreationerror",
a,!1);fa=l.getExtension("OES_texture_float")&&l.getExtension("OES_texture_float_linear");fa||(console.error("Your browser does not suppert OES_texture_float, trying OES_texture_half_float..."),(da=(ea=l.getExtension("OES_texture_half_float"))&&l.getExtension("OES_texture_half_float_linear"))||console.error("Your browser does not suppert OES_texture_half_float, will use 8-bit textures."));ba=!0}};function ka(a){var b;if(null==a||"object"!=typeof a)return a;if(a instanceof Array){b=[];for(var c=0,e=a.length;c<e;c++)b[c]=ka(a[c]);return b}if(a instanceof Object){b={};for(c in a)a.hasOwnProperty(c)&&0<="oper impl args ctype stack name modifs arglist value real imag key obj body".split(" ").indexOf(c)&&(b[c]=ka(a[c]));return b}}function la(a){return"number"===typeof a}
function ma(a,b){if(a===b)return!0;if(la(a)||la(b))return a===b;for(var c in a)if(a.hasOwnProperty(c)&&(!b.hasOwnProperty(c)||!ma(a[c],b[c])))return!1;for(var e in b)if(b.hasOwnProperty(e)&&!a.hasOwnProperty(e))return!1;return!0}function na(a){return-1===a.indexOf("$")?a:a.substr(0,a.indexOf("$"))}
function oa(a){if("boolean"===a.ctype)return w;if("number"===a.ctype)return a=a.value,1E-10>Math.abs(a.imag)?(a.real|0)===a.real?x:y:z;if("list"===a.ctype){var b=a.value;if(0<b.length){for(var c=oa(b[0]),e=1;e<b.length;e++)c=pa(c,oa(b[e]));if(B(c,y)){if(2==b.length)return C;if(3==b.length)return D;if(4==b.length)return E}if(B(c,z)&&2==b.length)return F;if(c===C&&2==b.length)return G;if(c===F&&2==b.length)return qa;if(c===D&&3==b.length)return ra;if(c===E&&4==b.length)return sa}}else if("string"===
a.ctype||"image"===a.ctype)return H;console.error("Cannot guess type of "+JSON.stringify(a));return n}var ta=0;function ua(){ta++;return"_helper"+ta}function va(a,b){if(a>g.width||b>g.height)g.width=Math.ceil(a),g.height=Math.ceil(b)}function wa(a,b,c){a=a.getInitialMatrix();b=b-a.tx;c+=a.ty;return{x:(b*a.d-c*a.b)/a.det,y:-(-b*a.c+c*a.a)/a.det}}function xa(a){return wa(a,0,a.instance.canvas.clientHeight)}function ya(a){return wa(a,a.instance.canvas.clientWidth,a.instance.canvas.clientHeight)}
var za=new Float32Array(1),Aa=new Int32Array(za.buffer);function Ba(a){za[0]=a;a=Aa[0];var b=a>>16&32768,c=(a&2147483647)+4096;if(1199570944<=c)return 1199570944<=(a&2147483647)?2139095040>c?b|31744:b|31744|(a&8388607)>>13:b|31743;if(947912704<=c)return b|c-939524096>>13;if(855638016>c)return b;c=(a&2147483647)>>23;return b|(a&8388607|8388608)+(8388608>>>c-102)>>126-c}
function Ca(a){if(fa)return new Float32Array(a);if(da){for(var b=new Uint16Array(a.length),c=0;c<a.length;c++)b[c]=Ba(a[c]);return b}b=new Uint8Array(a.length);for(c=0;c<a.length;c++)b[c]=255*a[c];return b}function Da(){return fa?l.FLOAT:da?ea.HALF_FLOAT_OES:l.UNSIGNED_BYTE}function Ea(a){for(var b=1;b<a;)b<<=1;return b};function Fa(a){a.hasOwnProperty("canvaswrapper")||(a.canvaswrapper=new Ga(a),a.ready||(console.error("Image not ready. Creating onload event."),a.whenReady(function(){a.canvaswrapper=new Ga(a);console.log("Image has been loaded now");ga++})));return a.canvaswrapper}
function Ga(a){this.l=a;this.i=a.width;this.h=a.height;this.B=Ea(this.i);this.C=Ea(this.h);this.o=0;a.live&&ca.push(this.M.bind(this));this.v=[];this.F=[];Ha(this);a.drawTo=this.drawTo.bind(this);a.cdyUpdate=this.N.bind(this);a=this.B*this.C*4;a=fa?new Float32Array(a):da?new Uint16Array(a):new Uint8Array(a);for(var b=0;2>b;b++)this.v[b]=l.createTexture(),l.bindTexture(l.TEXTURE_2D,this.v[b]),l.pixelStorei(l.UNPACK_ALIGNMENT,1),l.pixelStorei(l.UNPACK_FLIP_Y_WEBGL,1),l.texImage2D(l.TEXTURE_2D,0,l.RGBA,
this.B,this.C,0,l.RGBA,Da(),a),this.l.ready&&l.texSubImage2D(l.TEXTURE_2D,0,0,0,l.RGBA,Da(),this.l.img),l.pixelStorei(l.UNPACK_FLIP_Y_WEBGL,0),l.texParameteri(l.TEXTURE_2D,l.TEXTURE_MIN_FILTER,l.LINEAR),l.texParameteri(l.TEXTURE_2D,l.TEXTURE_MAG_FILTER,l.LINEAR),this.F[b]=l.createFramebuffer(),l.bindFramebuffer(l.FRAMEBUFFER,this.F[b]),l.framebufferTexture2D(l.FRAMEBUFFER,l.COLOR_ATTACHMENT0,l.TEXTURE_2D,this.v[b],0);this.A=new Ia(aa.copytexture_v,aa.copytexture_f);a=l.createBuffer();l.bindBuffer(l.ARRAY_BUFFER,
a);a=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]);b=l.getAttribLocation(this.A.h,"aPos");l.enableVertexAttribArray(b);var c=l.getAttribLocation(this.A.h,"aTexCoord");l.enableVertexAttribArray(c);var e=new Float32Array([0,0,1,0,0,1,1,1]),d=a.byteLength;l.bufferData(l.ARRAY_BUFFER,d+e.byteLength,l.STATIC_DRAW);l.bufferSubData(l.ARRAY_BUFFER,0,a);l.bufferSubData(l.ARRAY_BUFFER,d,e);l.vertexAttribPointer(b,3,l.FLOAT,!1,0,0);l.vertexAttribPointer(c,2,l.FLOAT,!1,0,d)}
function Ha(a){l.bindTexture(l.TEXTURE_2D,a.v[a.o])}Ga.prototype.bindFramebuffer=function(){l.bindFramebuffer(l.FRAMEBUFFER,this.F[this.o^1]);this.o^=1};Ga.prototype.N=function(){var a=this.l.img.getContext("2d");a.clearRect(0,0,this.i,this.h);this.drawTo(a,0,0)};Ga.prototype.M=function(){Ha(this);l.pixelStorei(l.UNPACK_FLIP_Y_WEBGL,1);l.texSubImage2D(l.TEXTURE_2D,0,0,0,l.RGBA,Da(),this.l.img);l.pixelStorei(l.UNPACK_FLIP_Y_WEBGL,0)};
Ga.prototype.drawTo=function(a,b,c){va(this.i,this.h);l.viewport(0,0,this.B,this.C);l.useProgram(this.A.h);l.activeTexture(l.TEXTURE0);l.bindTexture(l.TEXTURE_2D,this.v[this.o]);this.A.i.sampler([0]);l.bindFramebuffer(l.FRAMEBUFFER,null);l.drawArrays(l.TRIANGLE_STRIP,0,4);l.flush();a.drawImage(g,0,g.height-this.h,this.i,this.h,b,c,this.i,this.h)};function Ja(a,b){this.s=a;var c=Ka(new La(a),b);this.i=c.m;this.u=c.u;this.l=aa.standardFragmentHeader+c.code;this.o=aa.vshader;this.h=new Ia(this.o,this.l);c=l.createBuffer();l.bindBuffer(l.ARRAY_BUFFER,c);var c=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,1,1,0]),e=l.getAttribLocation(this.h.h,"aPos");l.enableVertexAttribArray(e);var d=l.getAttribLocation(this.h.h,"aTexCoord");l.enableVertexAttribArray(d);var f=new Float32Array([0,0,1,0,0,1,1,1]),h=c.byteLength;l.bufferData(l.ARRAY_BUFFER,h+f.byteLength,
l.STATIC_DRAW);l.bufferSubData(l.ARRAY_BUFFER,0,c);l.bufferSubData(l.ARRAY_BUFFER,h,f);l.vertexAttribPointer(e,3,l.FLOAT,!1,0,0);l.vertexAttribPointer(d,2,l.FLOAT,!1,0,h)}
function Ma(a,b,c,e,d,f){var h=d/e,m=b.x+-(c.y-b.y)*h,h=b.y+(c.x-b.x)*h;va(e,d);f?l.viewport(0,0,e,d):l.viewport(0,g.height-d,e,d);l.useProgram(a.h.h);b=[c.x-b.x,m-b.x,b.x,c.y-b.y,h-b.y,b.y,0,0,1];a.h.i.hasOwnProperty("transformMatrix")&&a.h.i.transformMatrix([b[0],b[3],b[6],b[1],b[4],b[7],b[2],b[5],b[8]]);for(var k in a.i)if(b=a.s.evaluateAndVal(a.i[k].w),d=a.i[k].type,c=a.h.i[k],void 0!==c)switch(d){case z:c([b.value.real,b.value.imag]);break;case w:b.value?c([1]):c([0]);break;case x:case y:c([b.value.real]);
break;case C:case D:case E:e=0;d===C&&(e=2);d===D&&(e=3);d===E&&(e=4);d=[];for(m=0;m<e;m++)d.push(b.value[m].value.real);c(d);break;case G:case ra:case sa:e=0;d===G&&(e=2);d===ra&&(e=3);d===sa&&(e=4);d=[];for(m=0;m<e;m++)for(h=0;h<e;h++)d.push(b.value[h].value[m].value.real);c(d);break;case F:c([b.value[0].value.real,b.value[0].value.imag,b.value[1].value.real,b.value[1].value.imag]);break;case qa:e=Array(16);for(d=0;2>d;d++)for(m=0;2>m;m++)h=b.value[d].value[m].value,e[8*m+2*d]=h.real,e[4*(2*m+1)+
2*d+1]=h.real,e[4*(2*m+1)+2*d]=-h.imag,e[8*m+2*d+1]=h.imag;c(e);break;default:console.error("Don't know how to set uniform"+k+", which has the type "+I(d)+", to "+b)}a.h.i.hasOwnProperty("rnd_")&&a.h.i.rnd_([Math.random()]);k=0;for(var p in a.u)l.activeTexture(l.TEXTURE0+k),b=a.u[p].name,c=a.u[p].h,Ha(c),a.h.i["_sampler"+b]([k]),a.h.i["_ratio"+b]([c.i/c.h]),a.h.i["_cropfact"+b]([c.i/c.B,c.h/c.C]),k++;f?f.bindFramebuffer():l.bindFramebuffer(l.FRAMEBUFFER,null);l.drawArrays(l.TRIANGLE_STRIP,0,4);l.flush()}
;createCindy.registerPlugin(1,"CindyGL",function(a){function b(b,e,d,f,h,m){if(!b.J||b.I<ga)b.J=!0,b.I=ga,b.L=new Ja(a,b);ca.forEach(function(a){return a()});Ma(b.L,e,d,f,h,m)}n=a.nada;a.defineFunction("compile",1,function(b){b=Ka(new La(a),b[0]);console.log(b);return{ctype:"string",value:b}});a.defineFunction("forcerecompile",0,function(){ga++;return n});a.defineFunction("colorplot",1,function(c){ia();var e=a.instance.canvas.clientWidth,d=a.instance.canvas.clientHeight,f=a.instance.canvas.width,h=
a.instance.canvas.height;b(c[0],xa(a),ya(a),f,h,null);a.instance.canvas.getContext("2d").drawImage(g,0,0,f,h,0,0,e,d);return n});a.defineFunction("colorplot",3,function(c){ia();var e=c[0],d=a.extractPoint(a.evaluateAndVal(c[1])),f=a.extractPoint(a.evaluateAndVal(c[2])),h={x:Math.min(d.x,f.x),y:Math.min(d.y,f.y)},m={x:Math.max(d.x,f.x),y:Math.min(d.y,f.y)};c=a.instance.canvas.clientWidth;var k=a.instance.canvas.clientHeight,p=a.instance.canvas.width,v=a.instance.canvas.height,A=wa(a,0,0),Y=xa(a),Z=
ya(a),Z=Math.abs((d.x-f.x)/(Y.x-Z.x)),A=Math.abs((d.y-f.y)/(A.y-Y.y));b(e,h,m,p*Z,v*A,null);e=a.instance.canvas.getContext("2d");h=Math.min(d.x,f.x);d=Math.max(d.y,f.y);f=a.getInitialMatrix();e.drawImage(g,0,0,p*Z,v*A,h*f.a-d*f.b+f.tx,h*f.c-d*f.d-f.ty,Z*c,A*k);return n});a.defineFunction("colorplot",4,function(c){ia();var e=a.extractPoint(a.evaluateAndVal(c[0])),d=a.extractPoint(a.evaluateAndVal(c[1])),f=a.evaluateAndVal(c[2]);c=c[3];if(!e.ok||!d.ok||"string"!==f.ctype)return n;var f=a.getImage(f.value,
!0),h=Fa(f);b(c,e,d,f.width,f.height,h);return n});a.defineFunction("colorplot",2,function(c){ia();var e=xa(a),d=ya(a),f=a.evaluateAndVal(c[0]);c=c[1];if("string"!==f.ctype)return n;var f=a.getImage(f.value,!0),h=Fa(f);b(c,e,d,f.width,f.height,h);return n});a.defineFunction("setpixel",4,function(b){var e;var d=a.evaluateAndVal(b[0]),f;f=void 0===f?null:f;"string"===d.ctype?e=d.value:(console.log("argument is not a string"),e=f);d=Na(a.evaluateAndVal(b[1]));f=Na(a.evaluateAndVal(b[2]));b=Oa(a.evaluateAndVal(b[3]));
if(!e)return n;var h=a.getImage(e,!0),h=Fa(h);isFinite(d)&&isFinite(f)&&e&&h&&b&&(Ha(h),e=[b[0],b[1],b[2],1],l.texSubImage2D(l.TEXTURE_2D,0,d,f,1,1,l.RGBA,Da(),Ca(e)),b=h.l.img.getContext("2d"),h=b.createImageData(1,1),h.data.d=e,b.putImageData(h,d,f));return n})});function B(a,b){return a===b?!0:la(a)&&la(b)?void 0===u[a]?!1:1073741824>u[a][b]:!1}var J=0;function pa(a,b){var c=void 0;if(B(b,a))return a;if(B(a,b)||!la(a))return b;if(!la(b))return a;for(var e=0;e<J;e++)B(a,e)&&B(b,e)&&(void 0===c?c=e:B(e,c)&&(c=e));return c}function Pa(a){return{index:a,type:"template"}}var K={};
function Qa(a,b){for(var c in K[a]){for(var e=K[a][c],d=b.length===e.f.length,f={},h=0;h<b.length&&d;h++)"template"===e.f[h].type?(void 0===f[e.f[h].index]&&(f[e.f[h].index]=[]),f[e.f[h].index].push(b[h])):d&=B(b[h],e.f[h]);if(d){var m={},k;for(k in f){m[k]=f[k][0];for(var p in f[k])m[k]=pa(m[k],f[k][p]),void 0===m[k]&&(d=!1)}if(d){c={f:[]};for(h=0;h<b.length&&d;h++)c.f[h]="template"===e.f[h].type?m[e.f[h].index]:e.f[h];c.g="template"===e.g.type?m[e.g.index]:e.g;return c}}}return n};var w=1,x=2,y=3,z=4,C=6,D=7,E=8,G=11,ra=12,sa=13,H=14,F=16,qa=17,Ra={O:w,T:x,S:y,P:z,da:5,$:C,ba:D,ca:E,color:9,Y:10,U:G,W:ra,X:sa,Z:H,R:15,aa:F,V:qa,image:18};Object.freeze(Ra);function I(a){return"bool int float complex voidt float[2] float[3] float[4] color point float[2,2] float[3,3] float[4,4] string 2D-Coordinate complex[2] complex[2,2] image".split(" ")[a-1]}t[w]=[x];t[x]=[y];t[y]=[z,9];t[D]=[9,10];t[E]=[9];t[10]=[15];t[C]=[15,F];t[z]=[15];t[G]=[qa];
var Sa={f:[w],g:w},Ta={f:[w,w],g:w},Ua={f:[x],g:x},L={f:[x,x],g:x},Va={f:[],g:y},M={f:[y],g:y},N={f:[y,y],g:y},O={f:[z],g:z},P={f:[z,z],g:z},Wa={f:[C,C],g:C},Xa={f:[D,D],g:D},Ya={f:[E,E],g:E},Za={f:[y],g:z},Q={f:[z],g:y},$a={f:[z,z],g:y},ab={f:[C],g:y},bb={f:[D],g:y},cb={f:[E],g:y},db={f:[C,C],g:y},eb={f:[D,D],g:y},fb={f:[E,E],g:y},gb={f:[x,x],g:w},hb={f:[y,y],g:w},R=Pa(1),ib=Pa(2),jb=Pa(3);K.sqrt=[Za,O];K.abs=[M,Q,ab,bb,cb];K.exp=[M,O];K.log=[Za,O];K.sin=[M,O];K.cos=[M,O];K.tan=[M,O];
K.arccos=[Za,O];K.arcsin=[Za,O];K.arctan=[M,O];K.arctan2=[N,P,Q,{f:[C],g:y},{f:[F],g:z}];K.add=[L,N,P,Wa,Xa,Ya];K.sub=[L,N,P,Wa,Xa,Ya,{f:[5,x],g:x},{f:[5,y],g:y},{f:[5,z],g:z},{f:[5,C],g:C},{f:[5,D],g:D},{f:[5,E],g:E}];K.mult=[L,N];var kb=[z,C,D,E];kb.forEach(function(a){K.mult.push({f:[y,a],g:a});K.mult.push({f:[a,y],g:a})});K.mult=K.mult.concat([P,{f:[G,C],g:C},{f:[qa,F],g:F},{f:[ra,D],g:D},{f:[sa,E],g:E}]);K.mult.push(db);K.mult.push(eb);K.mult.push(fb);K.div=[N,P];
kb.forEach(function(a){K.div.push({f:[a,y],g:a})});K.pow=[{f:[y,x],g:y},{f:[z,z],g:z}];K.re=[Q];K.conjugate=[O];K.im=[Q];K.round=[{f:[y],g:x},{f:[z],g:z}];K.floor=[{f:[y],g:x},{f:[z],g:z}];K.ceil=[{f:[y],g:x},{f:[z],g:z}];K.mod=[L,N,P];K.random=[Va,M,O];K.randominteger=[Ua];K.randomint=[Ua];K.seedrandom=[{f:[y],g:5}];K.randombool=[{f:[],g:w}];K.randomnormal=[{f:[],g:y}];K.dist=[N,$a,db,eb,fb];K._=[{f:[C,x],g:y},{f:[D,x],g:y},{f:[E,x],g:y},{f:[F,x],g:z}];K["^"]=K.pow;K["*"]=K.mult;K["/"]=K.div;
K["+"]=K.add;K["-"]=K.sub;[">","<",">=","<=","=="].forEach(function(a){return K[a]=[gb,hb]});K["&"]=[Ta];K["%"]=[Ta];K["="]=[{f:[R,ib],g:ib}];K[";"]=[{f:[R,5],g:R},{f:[R,ib],g:ib},{f:[R],g:R}];K.abs_infix=K.abs;K.dist_infix=K.dist;K.not=[Sa];K.and=[Ta];K.or=[Ta];K.xor=[Ta];"red green blue gray grey hue".split(" ").forEach(function(a){return K[a]=[{f:[y],g:D}]});K["if"]=[{f:[w,R,R],g:R},{f:[w,R,ib],g:5},{f:[w,R],g:R}];K.repeat=[{f:[x,R],g:R}];
K.apply=[{f:[{type:"list",length:R,K:ib},{type:"expression",f:ib,g:jb}],g:{type:"list",length:R,K:jb}}];K.min=[L,N];K.max=[L,N];K.complex=[{f:[C],g:z}];K.re=[Q];K.im=[Q];K.genList=[{f:[y,y],g:C},{f:[y,y,y],g:D},{f:[y,y,y,y],g:E},{f:[z,z],g:F}];K.imagergb=[{f:[H,15],g:D},{f:[15,15,H,15],g:D},{f:[18,15],g:D},{f:[15,15,18,15],g:D}];K.imagergba=[{f:[H,15],g:E},{f:[15,15,H,15],g:E},{f:[18,15],g:E},{f:[15,15,18,15],g:E}];Object.freeze(K);for(var lb in Ra)var mb=Ra[lb]+1,nb=J,J=nb>mb?nb:mb;
for(var u=Array(J),ha=Array(J),ob=0;ob<J;ob++){u[ob]=Array(J);ha[ob]=Array(J);for(var pb=0;pb<J;pb++)u[ob][pb]=1073741824,ha[ob][pb]=-1;u[ob][ob]=0}for(var qb=0;qb<J;qb++)for(var rb in t[qb]){var sb=t[qb][rb];u[qb][sb]=1;ha[qb][sb]=sb}for(var tb=0;tb<J;tb++)for(var ub=0;ub<J;ub++)for(var vb=0;vb<J;vb++)u[ub][tb]+u[tb][vb]<u[ub][vb]&&(u[ub][vb]=u[ub][tb]+u[tb][vb],ha[ub][vb]=ha[ub][tb]);Object.freeze(t);Object.freeze(u);Object.freeze(ha);var S={};function wb(a,b){if(!b.G.hasOwnProperty(a)){b.G[a]=!0;for(var c in S[a])wb(S[a][c],b);b.H.push(aa[a])}}function T(a){return function(b,c){wb(a,c);return U(a)(b)}};function La(a){this.o={};this.l={};this.h={};this.m={};this.G={};this.H=[];this.B={};this.A=[];this.v=!1;this.i={};this.s=a;this.u={}}function xb(a,b,c,e){if(!B(c,e))return console.error(I(c)+" is no subtype of "+I(e)+" (trying to cast the term "+b+")"),b;if(c===e)return b;var d=ha[c][e];return V.hasOwnProperty(c)&&V[c].hasOwnProperty(d)?xb(a,V[c][d](b,a),d,e):(console.error("CindyGL: No type-inclusion function for "+I(c)+" to "+I(d)+" found. \n Using identity"),xb(a,b,d,e))}
function yb(a,b,c){if(b.isuniform)return a.m[b.uvariable].type;if("variable"===b.ctype){b=b.name;if("#"===b)return C;if(a.h.hasOwnProperty(c)&&a.h[c].hasOwnProperty(b))return a.h[c][b];if(a.h.hasOwnProperty("")&&a.h[""].hasOwnProperty(b))return a.h[""][b]}else if("function"===b.ctype&&a.i.hasOwnProperty(b.oper)){if(a.h.hasOwnProperty("")&&a.h[""].hasOwnProperty(b.oper))return a.h[""][b.oper]}else{if("number"===b.ctype)return 0!==b.value.imag?z:(b.value.real|0)===b.value.real?x:y;if("void"===b.ctype)return 5;
if("field"===b.ctype)return y;if("string"===b.ctype)return H;for(var e=Array(b.args.length),d=0;d<b.args.length;d++)e[d]=zb(a,b.args[d],c);a=Qa(na(b.oper),e);return void 0===a||a===n?n:a.g}return n}function zb(a,b,c){a.v&&b.hasOwnProperty("computedType")||(b.computedType=yb(a,b,c));return b.computedType}
function Ab(a,b){function c(a,b){e.hasOwnProperty(b)||(e[b]=[]);d.hasOwnProperty(b)||(d[b]={});for(var k in a.args)c(a.args[k],b);if("="===a.oper){var p=a.args[0].name;k=b;-1===e[b].indexOf(p)&&(k="",-1===e[k].indexOf(p)&&(e[k].push(p),d[k][p]=[]));d[k][p].push({w:a.args[1],D:b})}else if(void 0!==a.oper&&"regional"===na(a.oper))for(p=0;p<a.args.length;p++)"variable"===a.args[p].ctype&&(k=a.args[p].name,-1===e[b].indexOf(k)&&(e[b].push(k),d[b][k]=[]));else if("function"===a.ctype&&f.hasOwnProperty(a.oper)){k=
a.oper;e.hasOwnProperty(k)||(e[k]=[]);d.hasOwnProperty(k)||(d[k]={});for(p in f[k].arglist){var v=f[k].arglist[p].name;e[k].push(v);d[k].hasOwnProperty(v)||(d[k][v]=[]);d[k][v].push({w:a.args[p],D:b})}c(f[k].body,k);-1===e[""].indexOf(k)&&(e[""].push(k),d[""][k]=[{w:f[k].body,D:k}])}}var e={},d={},f=a.i;c(b,"");a.o=e;a.l=d}
function Bb(a,b){function c(a,b){if(a.hasOwnProperty("dependsOnPixel")&&!0===a.dependsOnPixel)return!0;if("variable"===a.ctype){var e=a.name;return d.hasOwnProperty(b)&&d[b][e]||-1===f[b].indexOf(e)&&d.hasOwnProperty("")&&d[""][e]?a.dependsOnPixel=!0:a.dependsOnPixel=!1}for(e in a.args)if(c(a.args[e],b))return a.dependsOnPixel=!0;return"function"===a.ctype&&"random"===na(a.oper)||"function"===a.ctype&&h.hasOwnProperty(a.oper)&&(e=a.oper,d.hasOwnProperty(e)||(d[e]={}),c(h[e].body,e))?a.dependsOnPixel=
!0:"field"===a.ctype?a.dependsOnPixel=c(a.obj,b):!1}function e(a,b){if(c(a,b)){for(var d in a.args)e(a.args[d],b);"field"===a.ctype&&e(a.obj,b);"function"===a.ctype&&h.hasOwnProperty(a.oper)&&(d=a.oper,p.hasOwnProperty(d)||(p[d]=!0,e(h[d].body,d)))}else"number"!==a.ctype&&"string"!==a.ctype&&"image"!==a.ctype&&"void"!==a.ctype&&(d=ua(),a.isuniform=!0,a.uvariable=d,v[d]={w:a,type:n})}var d={"":{"#":!0}},f=a.o,h=a.i,m;for(m in a.l)for(var k in a.l[m])d.hasOwnProperty(m)||(d[m]={}),d[m][k]=!0;c(b,"");
var p={"":!0},v={};e(b,"");a.m=v}function Cb(a,b){if("function"===b.ctype&&!a.i.hasOwnProperty(b.oper)&&null!==a.s.getMyfunction(b.oper)){var c=b.oper;a.i[c]=ka(a.s.getMyfunction(c));Cb(a,a.i[c].body)}for(var e in b.args)Cb(a,b.args[e])}
function W(a,b,c,e){if(b.isuniform){b=b.uvariable;var d=a.m[b].type;return e?{code:"",j:d!=H?b:a.s.evaluateAndVal(a.m[b].w).value,type:d}:{code:""}}if(";"===b.oper){for(var d={type:5,j:""},f="",h=b.args.length-1,m=h;0<=m;m--)"void"===b.args[m].ctype&&h--;for(m=0;m<=h;m++)d=W(a,b.args[m],c,e&&m===h),f+=d.code;return e?{code:f,j:d.j,type:d.type}:{code:f}}if("="===b.oper)return d=W(a,b.args[1],c,!0),f=b.args[0].name,b=f+" = "+xb(a,d.j,d.type,zb(a,b.args[0],c)),e?{code:d.code,j:b,type:a.h[c][f]}:{code:d.code+
b+";\n"};if("repeat$2"===b.oper){if("number"!==b.args[0].ctype)return console.error("repeat possible only for fixed constant number in GLSL"),n;d=ua();f=b.args[0].value.real|0;b=W(a,b.args[1],c,e);m=h="";e&&(m=ua(),h+=q[b.type]+" "+m+";");h=h+("for(int "+d+"=0; "+d+" < "+f+"; "+d+"++) {\n")+b.code;e&&(h+=m+" = "+b.j+";\n");h+="}\n";return e?{code:h,j:m,type:b.type}:{code:h}}if("repeat$3"===b.oper)console.error("TODO");else{if("if$2"===b.oper||"if$3"===b.oper){var m=W(a,b.args[0],c,!0),k=W(a,b.args[1],
c,e),f=d="",h=zb(a,b,c);e&&(f=ua(),d+=q[h]+" "+f+";");d+=m.code;d+="if("+m.j+") {\n";d+=k.code;e&&(d+=f+" = "+xb(a,k.j,k.type,h)+";\n");"if$3"===b.oper&&(b=W(a,b.args[2],c,e),d=d+"} else {\n"+b.code,e&&(d+=f+" = "+xb(a,b.j,b.type,h)+";\n"));d+="}\n";return e?{code:d,j:f,type:h}:{code:d}}if("function"===b.ctype||"infix"===b.ctype){var p=b.oper;b=b.args.map(function(b){return W(a,b,c,!0)});f=b.map(function(a){return a.type});if(a.i.hasOwnProperty(p)){d=Db(a,p);h=Array(b.length);for(m=0;m<b.length;m++)h[m]=
a.h[p][a.i[p].arglist[m].name];m=a.h[""][p]}else{p=na(p);if("regional"===p)return e?{j:"",type:5,code:""}:{code:""};var v=Qa(p,f);if(v===n)return console.error("Could not find a signature for "+p+"("+f.map(I).join(", ")+").\nReturning empty code"),e?{j:"",type:5,code:""}:{code:""};h=v.f;m=v.g;d=n;for(k in r[p])if(ma(r[p][k][0],v)){d=r[p][k][1];break}d===n&&(console.error("There is no webgl-implementation for "+p+"("+v.f.map(I).join(", ")+").\ndefault: Try glsl-function with same name"),d=function(a){return p+
"("+a.join(", ")+")"})}for(var k="",v=Array(b.length),A=0;A<b.length;A++)k+=b[A].code,v[A]=xb(a,b[A].j,f[A],h[A]);b=d(v,a);return e?{j:b,type:m,code:k}:{code:k+b+";\n"}}if("number"===b.ctype)return f=zb(a,b,c),f===x?d=b.value.real|0:f===y?d=b.value.real:f===z&&(d="vec2( "+b.value.real+", "+b.value.imag+")"),e?{j:d,type:f,code:""}:{code:f+";\n"};if("string"===b.ctype)return d=H,b=b.value,e?{j:b,type:d,code:""}:{code:d+";\n"};if("variable"===b.ctype)return d=zb(a,b,c),b=b.name,"#"===b&&(b="cgl_pixel"),
e?{j:b,type:d,code:""}:{code:b+";\n"};if("void"===b.ctype)return e?{j:"",type:5,code:""}:{code:""};if("field"===b.ctype)return d=zb(a,b,c),f=W(a,b.obj,c,!0).j,f+="."+b.key,e?{j:f,type:d,code:""}:{code:f+";\n"}}console.error("dont know how to this.compile "+JSON.stringify(b))}function Db(a,b){Eb(a,b,a.i[b].arglist.length);return U(b)}
function Eb(a,b,c){if(!a.B.hasOwnProperty(b)){a.B[b]=!0;for(var e=a.i[b],d=Array(c),f=0;f<c;f++)d[f]=e.arglist[f].name;c=5===q[a.h[""][b]];var f=q[a.h[""][b]]+" "+na(b)+"("+d.map(function(c){return q[a.h[b][c]]+" "+c}).join(", ")+"){\n",h;for(h in a.o[b]){for(var m=!0,k=a.o[b][h],p=0;p<d.length;p++)m&=k!==d[p];m&&(f+=q[a.h[b][k]]+" "+k+";\n")}e=W(a,e.body,b,!c);f+=e.code;c||(f+="return "+xb(a,e.j,e.type,a.h[""][b])+";\n");a.A.push(f+"}\n")}}
function Ka(a,b){var c=b=ka(b);a.v=!1;Cb(a,c);Ab(a,c);Bb(a,c);for(var e in a.m)a.m[e].type=y,c=a.s.evaluateAndVal(a.m[e].w),a.m[e].type=oa(c),console.log("guessed type "+I(a.m[e].type)+" for "+JSON.stringify(a.m[e].w.name));for(e=!0;e;){e=!1;for(var d in a.l)for(var f in a.l[d])for(var h in a.l[d][f]){var c=zb(a,a.l[d][f][h].w,a.l[d][f][h].D),m=n;a.h.hasOwnProperty(d)&&a.h[d].hasOwnProperty(f)&&(m=a.h[d][f]);var k=m;c!==n&&(k=m===n?c:B(c,m)?m:pa(m,c),k!==n&&k!==m&&(a.h.hasOwnProperty(d)||(a.h[d]=
{}),a.h[d][f]=k,console.log("variable "+f+" in scope "+d+" got type "+I(k)+" (oltype/othertype is "+I(m)+"/"+I(c)+")"),e=!0))}}a.v=!0;d=W(a,b,"",!0);f=xb(a,d.j,d.type,9);B(d.type,9)||console.error("expression does not generate a color");var p;h=[];for(p in a.m)a.m[p].type!=H&&h.push("uniform "+q[a.m[p].type]+" "+p+";");p=h.join("\n");h="";for(var v in a.u)h+=a.u[v].code+"\n";p=p+h+a.H.join("\n");for(var A in a.o[""])v=a.o[""][A],a.i.hasOwnProperty(v)||(p+=q[a.h[""][v]]+" "+v+";\n");p+=a.A.join("\n");
p+="void main(void) {\n"+d.code+"gl_FragColor = "+f+";\n}\n";console.log(p);return{code:p,m:a.m,u:a.u}};function Fb(a,b){this.name=a;this.code=["uniform sampler2D _sampler",a,";uniform float _ratio",a,";uniform vec2 _cropfact",a,";vec4 _imagergba",a,"(vec2 A, vec2 B, vec2 p) {p -= A; B -= A;float b = dot(B,B);p = vec2(dot(p,B),_ratio",a,"*dot(p,vec2(-B.y,B.x)))/b;if(0. <= p.x && p.x <= 1. && 0. <= p.y && p.y <= 1.)return texture2D(_sampler",a,", p*_cropfact",a,");else return vec4(0.);}vec3 _imagergb",a,"(vec2 A, vec2 B, vec2 p) {return _imagergba",a,"(A, B, p).rgb;}"].join("");this.h=b}
function Gb(a){if("string"===typeof a)return a;a.hasOwnProperty("name")||(a.name=ua());return a.name}function Hb(a,b){var c=a[2],e=Gb(a[2]);"string"===typeof c&&(c=b.s.getImage(e,!0));if(null==c)return console.error("Could not find image "+e+"."),n;c=Fa(c);b.u.hasOwnProperty(e)||(b.u[e]=new Fb(e,c));return["_imagergba",e,"(",a[0],",",a[1],",",a[3],")"].join("")}function Ib(a,b){var c=Gb(a[2]);Hb(a,b);return["_imagergb",c,"(",a[0],",",a[1],",",a[3],")"].join("")}
function Jb(a,b){var c=Gb(a[0]);Hb(["",""].concat(a),b);var e=xa(b.s),d=ya(b.s);return["_imagergba",c,"(vec2(",e.x,",",e.y,"),vec2(",d.x,",",d.y,"), ",a[1],")"].join("")}function Kb(a,b){var c=Gb(a[0]);Hb(["",""].concat(a),b);var e=xa(b.s),d=ya(b.s);return["_imagergb",c,"(vec2(",e.x,",",e.y,"),vec2(",d.x,",",d.y,"), ",a[1],")"].join("")};q[w]="bool";q[x]="int";q[y]="float";q[z]="vec2";q[5]="void";q[C]="vec2";q[D]="vec3";q[E]="vec4";q[G]="mat2";q[ra]="mat3";q[sa]="mat4";q[9]="vec4";q[10]="vec3";q[15]="vec2";q[F]="vec4";q[qa]="mat4";Object.freeze(q);function U(a){return function(b){return na(a)+"("+b+")"}}function X(a){return function(b){return"("+b.join(a)+")"}}function Lb(a){return a}var V={},Mb;for(Mb in Ra)V[Ra[Mb]]={};V[w][x]=U("int");V[x][y]=U("float");V[y][z]=function(a){return"vec2("+a+", 0.)"};V[y][9]=T("float2color");
V[9][D]=function(a){return"("+a+").rgb"};V[9][E]=Lb;V[C][10]=function(a){return"vec3("+a+",1.0)"};V[D][9]=function(a){return"vec4("+a+",1.0)"};V[D][10]=Lb;V[E][9]=Lb;V[10][C]=T("dehomogenize");V[10][D]=Lb;V[10][15]=T("dehomogenize");V[C][15]=Lb;V[z][15]=Lb;V[C][F]=T("vec2complex");V[G][qa]=T("mat2complex");Object.freeze(V);r.sqrt=[[Za,T("sqrtf")],[O,T("sqrtc")]];r.abs=[[M,U("abs")],[Q,U("length")],[ab,U("length")],[bb,U("length")],[cb,U("length")]];r.abs_infix=r.abs;
r.dist=[[N,function(a){return U("abs")(X("-")(a))}],[$a,function(a){return U("length")(X("-")(a))}],[db,function(a){return U("length")(X("-")(a))}],[eb,function(a){return U("length")(X("-")(a))}],[fb,function(a){return U("length")(X("-")(a))}]];r.dist_infix=r.dist;r.sin=[[M,U("sin")],[O,T("sinc")]];r.cos=[[M,U("cos")],[O,T("cosc")]];r.tan=[[M,U("tan")],[O,T("tanc")]];r.exp=[[M,U("exp")],[O,T("expc")]];r.arctan=[[M,U("atan")],[O,T("arctanc")]];r.log=[[Za,T("logr")],[O,T("logc")]];r.add=[];r.sub=[];
[L,N,P,Wa,Xa,Ya].forEach(function(a){r.add.push([a,X("+")]);r.sub.push([a,X("-")])});function Nb(a){return"-("+a[1]+")"}[x,y,z,C,D,E].forEach(function(a){r.sub.push([{f:[5,a],g:a},Nb])});function Ob(a){return isFinite(a[1])?"("+a[0]+")["+(a[1]-1)+"]":"("+a[0]+")["+a[1]+"-1]"}
r._=[[{f:[C,x],g:y},Ob],[{f:[D,x],g:y},Ob],[{f:[E,x],g:y},Ob],[{f:[F,x],g:z},function(a){if(1===a[1])return"("+a[0]+").xy";if(2===a[1])return"("+a[0]+").zw";console.error("access of components of complex[2] only works for indeces that were hardcoded in CindyJS");return"ERROR: SEE CONSOLE (index was "+a[1]+") \n"}]];r["+"]=r.add;r["-"]=r.sub;
r.mult=[[L,X("*")],[N,X("*")],[P,T("multc")],[{f:[G,C],g:C},X("*")],[{f:[qa,F],g:F},X("*")],[{f:[ra,D],g:D},X("*")],[{f:[sa,E],g:E},X("*")],[db,U("dot")],[eb,U("dot")],[fb,U("dot")]];kb.forEach(function(a){r.mult.push([{f:[y,a],g:a},X("*")]);r.mult.push([{f:[a,y],g:a},X("*")])});r["*"]=r.mult;r.div=[[N,X("/")],[P,T("divc")]];kb.forEach(function(a){r.div.push([{f:[a,y],g:a},X("/")])});r["/"]=r.div;r.re=[[Q,T("realc")]];r.im=[[Q,T("imagc")]];
r.floor=[[{f:[y],g:x},function(a){return"int(floor("+a+"))"}],[{f:[z],g:z},U("floor")]];r.round=[[{f:[y],g:x},function(a){return"int(floor("+a+"+.5))"}],[{f:[z],g:z},function(a){return"floor("+a+"+vec2(.5))"}]];r.ceil=[[{f:[y],g:x},function(a){return"int(ceil("+a+"))"}],[{f:[z],g:z},U("ceil")]];r.mod=[[L,X("%")],[N,U("mod")],[P,U("mod")]];r.random=[[Va,T("random")],[M,function(a,b){return T("random")([],b)+"*"+a[0]}],[O,function(a,b){return"vec2("+T("random")([],b)+","+T("random")([],b)+")*"+a[0]}]];
r.arctan2=[[N,function(a){return"atan("+a[1]+", "+a[0]+")"}],[P,T("arctan2c")],[Q,T("arctan2vec2")],[{f:[C],g:y},T("arctan2vec2")],[{f:[F],g:z},T("arctan2vec2c")]];["red","green","blue","gray","hue"].forEach(function(a){return r[a]=[[{f:[y],g:D},T(a)]]});r.grey=r.gray;r.min=[[L,U("min")],[N,U("min")]];r.max=[[L,U("max")],[N,U("max")]];r.complex=[[{f:[C],g:z},Lb]];r.pow=[[{f:[y,x],g:y},function(a){return"pow("+a[0]+", float("+a[1]+"))"}],[{f:[z,z],g:z},T("powc")]];r["^"]=r.pow;
r.re=[[Q,function(a){return"("+a+").x"}]];r.conjugate=[[O,T("conjugate")]];r.im=[[Q,function(a){return"("+a+").y"}]];r.genList=[[{f:[y,y],g:C},U("vec2")],[{f:[y,y,y],g:D},U("vec3")],[{f:[y,y,y,y],g:E},U("vec4")],[{f:[z,z],g:F},U("vec4")]];r["&"]=[[Ta,X("&&")]];r["%"]=[[Ta,X("||")]];[">","<",">=","<=","=="].forEach(function(a){return r[a]=[[gb,X(a)],[hb,X(a)]]});r.imagergb=[[{f:[H,15],g:D},Kb],[{f:[15,15,H,15],g:D},Ib],[{f:[18,15],g:D},Kb],[{f:[15,15,18,15],g:D},Ib]];
r.imagergba=[[{f:[H,15],g:E},Jb],[{f:[15,15,H,15],g:E},Hb],[{f:[18,15],g:E},Jb],[{f:[15,15,18,15],g:E},Hb]];Object.freeze(r);S.divc=["multc"];S.powc=["expc","multc","logc"];S.sqrtc=["expc","multc","logc"];S.arccosc=["multc","negc","sqrtc","addc","logc"];S.arcsinc=["multc","negc","sqrtc","addc","logc"];S.tanc=["sinc","cosc","divc"];S.arctanc=["logc","addc","multc","subc"];S.arctan2c=["logc","divc","sqrtc","multc"];S.arctan2vec2c=["arctan2c"];S.hue=["hsv2rgb"];Object.freeze(S);function Pb(a){var b;b=void 0===b?null:b;return"list"!==a.ctype?(console.log("argument is not a list"),b):a.value}function Oa(a){var b;b=void 0===b?[.5,.5,.5]:b;if("number"===a.ctype){var c=Qb(a);if(!isNaN(c))return[c,c,c]}a=Pb(a);return null===a?b:3!=a.length?(console.log("Not an RGB color vector"),b):a.map(function(a){return Qb(a)})}
function Na(a){var b;b=void 0===b?Number.NaN:b;if("number"!==a.ctype)return console.log("argument is not a number"),b;b=a.value;a=b.real;b=b.imag;0!==b&&console.log("complex number is not real");b=Math.round(a);b!==a&&console.log("number is not an integer");return b}
function Qb(a){var b;b=void 0===b?Number.NaN:b;b=void 0===b?Number.NaN:b;"number"!==a.ctype?(console.log("argument is not a number"),a=b):(a=a.value,b=a.real,0!==a.imag&&console.log("complex number is not real"),a=b);return 0>a?0:1<a?1:a};function ja(a){this.h=a}ja.prototype.toString=function(){return this.h};
function Ia(a,b){var c=l;this.h=c.createProgram();Rb(this,c,c.VERTEX_SHADER,a);Rb(this,c,c.FRAGMENT_SHADER,b);var e=this.h;c.linkProgram(e);if(!c.getProgramParameter(e,c.LINK_STATUS))throw new ja("Error linking shader:\n"+c.getProgramInfoLog(e));c.validateProgram(e);if(!c.getProgramParameter(e,c.VALIDATE_STATUS))throw new ja("Error validating shader:\n"+c.getProgramInfoLog(e));var d,f=this.h,h,m,k,p={},v,A,Y,Z;d=c.getProgramParameter(f,c.ACTIVE_UNIFORMS);for(e=0;e<d;++e)if(h=c.getActiveUniform(f,
e),null!==h&&(m=h.name.replace(/\]/g,""))){for(v=p;null!==(k=/[.\[]/.exec(m));)A=m.substr(0,k.index),v.hasOwnProperty(A)?v=v[A]:"."===k[0]?v=v[A]={}:v=v[A]=[],m=m.substr(k.index+1);if(1<h.size){k=h.size;Z=Array(k);for(A=0;A<k;++A)Y=h.name+"["+A+"]",Y=Sb(this,c,Y,h),Z[A]=Y;v[m]=Z}else Y=Sb(this,c,h.name,h),v[m]=Y}this.i=p}
function Rb(a,b,c,e){c=b.createShader(c);b.shaderSource(c,e);b.compileShader(c);if(!b.getShaderParameter(c,b.COMPILE_STATUS))throw console.warn(e.split("\n")),new ja("Error compiling shader:\n"+b.getShaderInfoLog(c));b.attachShader(a.h,c)}
function Sb(a,b,c,e){a=b.getUniformLocation(a.h,c);switch(e.type){case b.FLOAT:return b.uniform1fv.bind(b,a);case b.FLOAT_VEC2:return b.uniform2fv.bind(b,a);case b.FLOAT_VEC3:return b.uniform3fv.bind(b,a);case b.FLOAT_VEC4:return b.uniform4fv.bind(b,a);case b.BOOL:case b.INT:case b.SAMPLER_2D:case b.SAMPLER_CUBE:return b.uniform1iv.bind(b,a);case b.BOOL_VEC2:case b.INT_VEC2:return b.uniform2iv.bind(b,a);case b.BOOL_VEC3:case b.INT_VEC3:return b.uniform3iv.bind(b,a);case b.BOOL_VEC4:case b.INT_VEC4:return b.uniform4iv.bind(b,
a);case b.FLOAT_MAT2:return b.uniformMatrix2fv.bind(b,a,!1);case b.FLOAT_MAT3:return b.uniformMatrix3fv.bind(b,a,!1);case b.FLOAT_MAT4:return b.uniformMatrix4fv.bind(b,a,!1);default:throw new ja("Unknown data type for uniform "+c);}};
})();//# sourceMappingURL=CindyGL.js.map


